struct style styles[] = {
	{ ".c", {
		{ "//", 2, CYELLOW, false },

		{ ">=", 2, CYELLOW, false },
		{ "<=", 2, CYELLOW, false },
		{ "+=", 2, CYELLOW, false },
		{ "-=", 2, CYELLOW, false },
		{ "*=", 2, CYELLOW, false },
		{ "/=", 2, CYELLOW, false },
		{ "==", 2, CYELLOW, false },
		{ ">>", 2, CYELLOW, false },
		{ "<<", 2, CYELLOW, false },
		{ "&&", 2, CYELLOW, false },
		{ "||", 2, CYELLOW, false },
		{ "++", 2, CYELLOW, false },
		{ "--", 2, CYELLOW, false },
		{ "=", 1, CYELLOW, false },
		{ "+", 1, CYELLOW, false },
		{ "-", 1, CYELLOW, false },
		{ "*", 1, CYELLOW, false },
		{ "/", 1, CYELLOW, false },
		{ "!", 1, CYELLOW, false },
		{ "~", 1, CYELLOW, false },
		{ "|", 1, CYELLOW, false },
		{ "&", 1, CYELLOW, false },
		{ "<", 1, CYELLOW, false },
		{ ">", 1, CYELLOW, false },
		{ "?", 1, CYELLOW, false },
		{ "'", 1, CYELLOW, false },
		{ "\"", 1, CYELLOW, false },

		{ "void", 4, CBLUE, true },
		{ "char", 4, CBLUE, true },
		{ "short", 5, CBLUE, true },
		{ "int", 3, CBLUE, true },
		{ "long", 4, CBLUE, true },
		{ "bool", 4, CBLUE, true },
		{ "float", 5, CBLUE, true },
		{ "double", 6, CBLUE, true },
		{ "const", 5, CBLUE, true },
		{ "unsigned", 8, CBLUE, true },

		{ "for", 3, CRED, true },
		{ "if", 3, CRED, true },
		{ "else", 4, CRED, true },
		{ "while", 5, CRED, true },
		{ "struct", 6, CRED, true },
		{ "static", 6, CRED, true },
		{ "enum", 4, CRED, true },
		{ "return", 6, CRED, true },
		{ "typedef", 7, CRED, true },
		{ "switch", 6, CRED, true },
		{ "case", 4, CRED, true },
		{ "default", 7, CRED, true },
		{ "break", 5, CRED, true },
		{ "continue", 8, CRED, true },

		{ "true", 4, CTEAL, true },
		{ "false", 5, CTEAL, true },

		{ "#include", 8, CGREEN, true },
		{ "#define", 7, CGREEN, true },
		{ "#ifdef", 6, CGREEN, true },
		{ "#ifndef", 7, CGREEN, true },
		{ "#endif", 6, CGREEN, true },

		{ "", 0, "", 0 },
	}},
	
};
