#ifndef __VIDD_CONFIG_SYNTAX_H__
#define __VIDD_CONFIG_SYNTAX_H__

#define ACTIVE_CLIENT_COLOR BRGB("255", "255", "0") FRGB("0", "0", "0")
#define INACTIVE_CLIENT_COLOR BRGB("255", "255", "255") FRGB("0", "0", "0")

#define SSID_KEYWORD "#"
#define SSID_OPERATOR "+"
#define SSID_MACRO ")"
#define SSID_TYPE "%"
#define SSID_COMMENT "/"
#define SSID_CONST "*"
#define SSID_STRING "\""
#define SSID_CHARACTER_LITERAL "'"
#define SSID_RANGE "~"
#define SSID_RANGE_NI "`"
#define SSID_NUMBER "$"

#define SCID_KEYWORD '#'
#define SCID_OPERATOR '+'
#define SCID_MACRO ')'
#define SCID_TYPE '%'
#define SCID_COMMENT '/'
#define SCID_CONST '*'
#define SCID_STRING '"'
#define SCID_CHARACTER_LITERAL '\''
#define SCID_RANGE '~'
#define SCID_RANGE_NI '`'
#define SCID_NUMBER '$'

#define SYNTAX_KEYWORD_COLOR FRGB("255", "255", "0")
#define SYNTAX_OPERATOR_COLOR FRGB("255", "255", "0")
#define SYNTAX_MACRO_COLOR FRGB("0", "255", "255")
#define SYNTAX_TYPE_COLOR FRGB("255", "0", "0")
#define SYNTAX_STRING_COLOR FRGB("255", "0", "255")
#define SYNTAX_COMMENT_COLOR STYLE_ITALIC FRGB("0", "0", "255")
#define SYNTAX_CONST_COLOR STYLE_ITALIC FRGB("0", "255", "255")
#define SYNTAX_CHARACTER_LITERAL_COLOR FRGB("155", "100", "0")
#define SYNTAX_NUMBER_COLOR FRGB("0", "255", "0")

char* SYNTAX_COLORS[] = {
	[SCID_KEYWORD]=SYNTAX_KEYWORD_COLOR,
	[SCID_OPERATOR]=SYNTAX_OPERATOR_COLOR,
	[SCID_MACRO]=SYNTAX_MACRO_COLOR,
	[SCID_TYPE]=SYNTAX_TYPE_COLOR,
	[SCID_COMMENT]=SYNTAX_COMMENT_COLOR,
	[SCID_CONST]=SYNTAX_CONST_COLOR,
	[SCID_STRING]=SYNTAX_STRING_COLOR,
	[SCID_CHARACTER_LITERAL]=SYNTAX_CHARACTER_LITERAL_COLOR,
	[SCID_NUMBER]=SYNTAX_NUMBER_COLOR,
};

#define SYNTAXES_ADD(syntax) \
	(char**)syntax,

#define SYNTAX_NEW(name) \
	char* name[] = {
#define SYNTAX_EXT_COUNT(count) \
	(char*)count,
#define SYNTAX_ADD_EXT(ext) \
	ext,
#define SYNTAX_ADD(name) \
	name,
#define SYNTAX_ADD_RANGE(start, end) \
	SSID_RANGE start "\0" end,
#define SYNTAX_ADD_RANGE_NI(start, end) \
	SSID_RANGE_NI start "\0" end,
#define SYNTAX_END(name) \
	0 };

SYNTAX_NEW(syntax_c)
	SYNTAX_EXT_COUNT(2)
	SYNTAX_ADD_EXT(".c")
	SYNTAX_ADD_EXT(".h")
	SYNTAX_ADD(SSID_KEYWORD "if")
	SYNTAX_ADD(SSID_KEYWORD "break")
	SYNTAX_ADD(SSID_KEYWORD "else")
	SYNTAX_ADD(SSID_KEYWORD "for")
	SYNTAX_ADD(SSID_KEYWORD "while")
	SYNTAX_ADD(SSID_KEYWORD "do")
	SYNTAX_ADD(SSID_KEYWORD "continue")
	SYNTAX_ADD(SSID_KEYWORD "switch")
	SYNTAX_ADD(SSID_KEYWORD "case")
	SYNTAX_ADD(SSID_KEYWORD "default")
	SYNTAX_ADD(SSID_KEYWORD "sizeof")
	SYNTAX_ADD(SSID_KEYWORD "typeof")
	SYNTAX_ADD(SSID_KEYWORD "return")
	SYNTAX_ADD(SSID_TYPE "struct")
	SYNTAX_ADD(SSID_TYPE "union")
	SYNTAX_ADD(SSID_TYPE "typedef")
	SYNTAX_ADD(SSID_TYPE "enum")
	SYNTAX_ADD(SSID_TYPE "register")
	SYNTAX_ADD(SSID_TYPE "static")
	SYNTAX_ADD(SSID_TYPE "const")
	SYNTAX_ADD(SSID_TYPE "extern")
	SYNTAX_ADD(SSID_TYPE "void")
	SYNTAX_ADD(SSID_TYPE "char")
	SYNTAX_ADD(SSID_TYPE "byte")
	SYNTAX_ADD(SSID_TYPE "bool")
	SYNTAX_ADD(SSID_TYPE "short")
	SYNTAX_ADD(SSID_TYPE "int")
	SYNTAX_ADD(SSID_TYPE "long")
	SYNTAX_ADD(SSID_TYPE "float")
	SYNTAX_ADD(SSID_TYPE "double")
	SYNTAX_ADD(SSID_TYPE "signed")
	SYNTAX_ADD(SSID_TYPE "unsigned")
	SYNTAX_ADD(SSID_TYPE "size_t")
	SYNTAX_ADD(SSID_TYPE "wchar_t")
	SYNTAX_ADD(SSID_TYPE "char8_t")
	SYNTAX_ADD(SSID_TYPE "char16_t")
	SYNTAX_ADD(SSID_TYPE "char32_t")
	SYNTAX_ADD(SSID_TYPE "int8_t")
	SYNTAX_ADD(SSID_TYPE "int16_t")
	SYNTAX_ADD(SSID_TYPE "int32_t")
	SYNTAX_ADD(SSID_TYPE "int64_t")
	SYNTAX_ADD(SSID_TYPE "uint8_t")
	SYNTAX_ADD(SSID_TYPE "uint16_t")
	SYNTAX_ADD(SSID_TYPE "uint32_t")
	SYNTAX_ADD(SSID_TYPE "uint64_t")
	SYNTAX_ADD(SSID_TYPE "uintmax_t")
	SYNTAX_ADD(SSID_TYPE "intmax_t")
	SYNTAX_ADD(SSID_TYPE "FILE")
	SYNTAX_ADD(SSID_CONST "true")
	SYNTAX_ADD(SSID_CONST "false")
	SYNTAX_ADD_RANGE(SSID_COMMENT "//", "\0")
	SYNTAX_ADD_RANGE(SSID_COMMENT "/*", "*/")
	SYNTAX_ADD_RANGE(SSID_MACRO "#", "\0")
	SYNTAX_ADD_RANGE(SSID_STRING "\"", "\"")
	SYNTAX_ADD_RANGE(SSID_CHARACTER_LITERAL "'", "'")
	SYNTAX_ADD(SSID_OPERATOR "=")
	SYNTAX_ADD(SSID_OPERATOR "!")
	SYNTAX_ADD(SSID_OPERATOR "+")
	SYNTAX_ADD(SSID_OPERATOR "-")
	SYNTAX_ADD(SSID_OPERATOR "*")
	SYNTAX_ADD(SSID_OPERATOR "/")
	SYNTAX_ADD(SSID_OPERATOR "~")
	SYNTAX_ADD(SSID_OPERATOR "<")
	SYNTAX_ADD(SSID_OPERATOR ">")
	SYNTAX_ADD(SSID_OPERATOR "?")
	SYNTAX_ADD(SSID_OPERATOR ":")
	SYNTAX_ADD(SSID_OPERATOR "&")
	SYNTAX_ADD(SSID_OPERATOR "%")
	SYNTAX_ADD(SSID_OPERATOR "~")
	SYNTAX_ADD(SSID_OPERATOR "|")
	SYNTAX_ADD(SSID_OPERATOR "^")
SYNTAX_END(syntax_c)

SYNTAX_NEW(syntax_cpp)
	SYNTAX_EXT_COUNT(4)
	SYNTAX_ADD_EXT(".cpp")
	SYNTAX_ADD_EXT(".cc")
	SYNTAX_ADD_EXT(".cxx")
	SYNTAX_ADD_EXT(".hpp")
	SYNTAX_ADD(SSID_KEYWORD "if")
	SYNTAX_ADD(SSID_KEYWORD "break")
	SYNTAX_ADD(SSID_KEYWORD "else")
	SYNTAX_ADD(SSID_KEYWORD "for")
	SYNTAX_ADD(SSID_KEYWORD "continue")
	SYNTAX_ADD(SSID_KEYWORD "while")
	SYNTAX_ADD(SSID_KEYWORD "do")
	SYNTAX_ADD(SSID_KEYWORD "switch")
	SYNTAX_ADD(SSID_KEYWORD "case")
	SYNTAX_ADD(SSID_KEYWORD "default")
	SYNTAX_ADD(SSID_KEYWORD "sizeof")
	SYNTAX_ADD(SSID_KEYWORD "typeof")
	SYNTAX_ADD(SSID_KEYWORD "return")
	SYNTAX_ADD(SSID_KEYWORD "using")
	SYNTAX_ADD(SSID_KEYWORD "try")
	SYNTAX_ADD(SSID_KEYWORD "catch")
	SYNTAX_ADD(SSID_KEYWORD "new")
	SYNTAX_ADD(SSID_KEYWORD "delete")
	SYNTAX_ADD(SSID_KEYWORD "dynamic_cast")
	SYNTAX_ADD(SSID_KEYWORD "static_cast")
	SYNTAX_ADD(SSID_KEYWORD "const_cast")
	SYNTAX_ADD(SSID_KEYWORD "this")
	SYNTAX_ADD(SSID_TYPE "constexpr")
	SYNTAX_ADD(SSID_TYPE "consteval")
	SYNTAX_ADD(SSID_TYPE "concept")
	SYNTAX_ADD(SSID_TYPE "struct")
	SYNTAX_ADD(SSID_TYPE "class")
	SYNTAX_ADD(SSID_TYPE "namespace")
	SYNTAX_ADD(SSID_TYPE "template")
	SYNTAX_ADD(SSID_TYPE "typename")
	SYNTAX_ADD(SSID_TYPE "typedef")
	SYNTAX_ADD(SSID_TYPE "enum")
	SYNTAX_ADD(SSID_TYPE "register")
	SYNTAX_ADD(SSID_TYPE "static")
	SYNTAX_ADD(SSID_TYPE "const")
	SYNTAX_ADD(SSID_TYPE "extern")
	SYNTAX_ADD(SSID_TYPE "void")
	SYNTAX_ADD(SSID_TYPE "char")
	SYNTAX_ADD(SSID_TYPE "byte")
	SYNTAX_ADD(SSID_TYPE "bool")
	SYNTAX_ADD(SSID_TYPE "short")
	SYNTAX_ADD(SSID_TYPE "int")
	SYNTAX_ADD(SSID_TYPE "long")
	SYNTAX_ADD(SSID_TYPE "float")
	SYNTAX_ADD(SSID_TYPE "double")
	SYNTAX_ADD(SSID_TYPE "signed")
	SYNTAX_ADD(SSID_TYPE "unsigned")
	SYNTAX_ADD(SSID_TYPE "size_t")
	SYNTAX_ADD(SSID_TYPE "wchar_t")
	SYNTAX_ADD(SSID_TYPE "char8_t")
	SYNTAX_ADD(SSID_TYPE "char16_t")
	SYNTAX_ADD(SSID_TYPE "char32_t")
	SYNTAX_ADD(SSID_TYPE "int8_t")
	SYNTAX_ADD(SSID_TYPE "int16_t")
	SYNTAX_ADD(SSID_TYPE "int32_t")
	SYNTAX_ADD(SSID_TYPE "int64_t")
	SYNTAX_ADD(SSID_TYPE "uint8_t")
	SYNTAX_ADD(SSID_TYPE "uint16_t")
	SYNTAX_ADD(SSID_TYPE "uint32_t")
	SYNTAX_ADD(SSID_TYPE "uint64_t")
	SYNTAX_ADD(SSID_TYPE "uintmax_t")
	SYNTAX_ADD(SSID_TYPE "intmax_t")
	SYNTAX_ADD(SSID_TYPE "FILE")
	SYNTAX_ADD(SSID_CONST "true")
	SYNTAX_ADD(SSID_CONST "false")
	SYNTAX_ADD_RANGE(SSID_COMMENT "//", "\0")
	SYNTAX_ADD_RANGE(SSID_COMMENT "/*", "*/")
	SYNTAX_ADD_RANGE(SSID_MACRO "#", "\0")
	SYNTAX_ADD_RANGE(SSID_STRING "\"", "\"")
	SYNTAX_ADD_RANGE(SSID_CHARACTER_LITERAL "'", "'")
	SYNTAX_ADD(SSID_OPERATOR "=")
	SYNTAX_ADD(SSID_OPERATOR "!")
	SYNTAX_ADD(SSID_OPERATOR "+")
	SYNTAX_ADD(SSID_OPERATOR "-")
	SYNTAX_ADD(SSID_OPERATOR "*")
	SYNTAX_ADD(SSID_OPERATOR "/")
	SYNTAX_ADD(SSID_OPERATOR "~")
	SYNTAX_ADD(SSID_OPERATOR "<")
	SYNTAX_ADD(SSID_OPERATOR ">")
	SYNTAX_ADD(SSID_OPERATOR "?")
	SYNTAX_ADD(SSID_OPERATOR ":")
	SYNTAX_ADD(SSID_OPERATOR "&")
	SYNTAX_ADD(SSID_OPERATOR "%")
	SYNTAX_ADD(SSID_OPERATOR "~")
	SYNTAX_ADD(SSID_OPERATOR "|")
	SYNTAX_ADD(SSID_OPERATOR "^")
	SYNTAX_ADD(SSID_OPERATOR "=")
	SYNTAX_ADD(SSID_OPERATOR "!")
	SYNTAX_ADD(SSID_OPERATOR "+")
	SYNTAX_ADD(SSID_OPERATOR "-")
	SYNTAX_ADD(SSID_OPERATOR "*")
	SYNTAX_ADD(SSID_OPERATOR "/")
	SYNTAX_ADD(SSID_OPERATOR "~")
	SYNTAX_ADD(SSID_OPERATOR "<")
	SYNTAX_ADD(SSID_OPERATOR ">")
	SYNTAX_ADD(SSID_OPERATOR "?")
	SYNTAX_ADD(SSID_OPERATOR ":")
	SYNTAX_ADD(SSID_OPERATOR "&")
	SYNTAX_ADD(SSID_OPERATOR "%")
	SYNTAX_ADD(SSID_OPERATOR "~")
	SYNTAX_ADD(SSID_OPERATOR "|")
	SYNTAX_ADD(SSID_OPERATOR "^")
SYNTAX_END(syntax_cpp)

SYNTAX_NEW(syntax_py)
	SYNTAX_EXT_COUNT(1)
	SYNTAX_ADD_EXT(".py")
	SYNTAX_ADD(SSID_KEYWORD "if")
	SYNTAX_ADD(SSID_KEYWORD "with")
	SYNTAX_ADD(SSID_KEYWORD "in")
	SYNTAX_ADD(SSID_KEYWORD "is")
	SYNTAX_ADD(SSID_KEYWORD "as")
	SYNTAX_ADD(SSID_KEYWORD "and")
	SYNTAX_ADD(SSID_KEYWORD "or")
	SYNTAX_ADD(SSID_KEYWORD "not")
	SYNTAX_ADD(SSID_KEYWORD "lambda")
	SYNTAX_ADD(SSID_KEYWORD "break")
	SYNTAX_ADD(SSID_KEYWORD "assert")
	SYNTAX_ADD(SSID_KEYWORD "continue")
	SYNTAX_ADD(SSID_KEYWORD "else")
	SYNTAX_ADD(SSID_KEYWORD "elif")
	SYNTAX_ADD(SSID_KEYWORD "for")
	SYNTAX_ADD(SSID_KEYWORD "while")
	SYNTAX_ADD(SSID_KEYWORD "return")
	SYNTAX_ADD(SSID_KEYWORD "try")
	SYNTAX_ADD(SSID_KEYWORD "catch")
	SYNTAX_ADD(SSID_KEYWORD "except")
	SYNTAX_ADD(SSID_KEYWORD "finally")
	SYNTAX_ADD(SSID_KEYWORD "yield")
	SYNTAX_ADD(SSID_KEYWORD "def")
	SYNTAX_ADD(SSID_KEYWORD "pass")
	SYNTAX_ADD(SSID_KEYWORD "raise")
	SYNTAX_ADD(SSID_KEYWORD "del")
	SYNTAX_ADD(SSID_KEYWORD "global")
	SYNTAX_ADD(SSID_KEYWORD "nonlocal")
	SYNTAX_ADD(SSID_KEYWORD "class")
	SYNTAX_ADD(SSID_TYPE "bool")
	SYNTAX_ADD(SSID_TYPE "int")
	SYNTAX_ADD(SSID_TYPE "float")
	SYNTAX_ADD(SSID_TYPE "len")
	SYNTAX_ADD(SSID_TYPE "open")
	SYNTAX_ADD(SSID_CONST "True")
	SYNTAX_ADD(SSID_CONST "False")
	SYNTAX_ADD(SSID_CONST "None")
	SYNTAX_ADD(SSID_MACRO "import")
	SYNTAX_ADD(SSID_MACRO "from")
	SYNTAX_ADD_RANGE(SSID_COMMENT "#", "\0")
	SYNTAX_ADD_RANGE(SSID_COMMENT "\"\"\"", "\"\"\"")
	SYNTAX_ADD_RANGE(SSID_STRING "\"", "\"")
	SYNTAX_ADD_RANGE(SSID_CHARACTER_LITERAL "'", "'")
	SYNTAX_ADD(SSID_OPERATOR "=")
	SYNTAX_ADD(SSID_OPERATOR "!")
	SYNTAX_ADD(SSID_OPERATOR "+")
	SYNTAX_ADD(SSID_OPERATOR "-")
	SYNTAX_ADD(SSID_OPERATOR "*")
	SYNTAX_ADD(SSID_OPERATOR "/")
	SYNTAX_ADD(SSID_OPERATOR "~")
	SYNTAX_ADD(SSID_OPERATOR "<")
	SYNTAX_ADD(SSID_OPERATOR ">")
	SYNTAX_ADD(SSID_OPERATOR "?")
	SYNTAX_ADD(SSID_OPERATOR ":")
	SYNTAX_ADD(SSID_OPERATOR "&")
	SYNTAX_ADD(SSID_OPERATOR "%")
	SYNTAX_ADD(SSID_OPERATOR "~")
	SYNTAX_ADD(SSID_OPERATOR "|")
	SYNTAX_ADD(SSID_OPERATOR "^")
SYNTAX_END(syntax_py)

SYNTAX_NEW(syntax_js)
	SYNTAX_EXT_COUNT(2)
	SYNTAX_ADD_EXT(".js")
	SYNTAX_ADD_EXT(".jsx")
	SYNTAX_ADD(SSID_KEYWORD "if")
	SYNTAX_ADD(SSID_KEYWORD "class")
	SYNTAX_ADD(SSID_KEYWORD "abstract")
	SYNTAX_ADD(SSID_KEYWORD "arguments")
	SYNTAX_ADD(SSID_KEYWORD "boolean")
	SYNTAX_ADD(SSID_KEYWORD "break")
	SYNTAX_ADD(SSID_KEYWORD "byte")
	SYNTAX_ADD(SSID_KEYWORD "case")
	SYNTAX_ADD(SSID_KEYWORD "catch")
	SYNTAX_ADD(SSID_KEYWORD "char")
	SYNTAX_ADD(SSID_KEYWORD "const")
	SYNTAX_ADD(SSID_KEYWORD "continue")
	SYNTAX_ADD(SSID_KEYWORD "debugger")
	SYNTAX_ADD(SSID_KEYWORD "default")
	SYNTAX_ADD(SSID_KEYWORD "delete")
	SYNTAX_ADD(SSID_KEYWORD "do")
	SYNTAX_ADD(SSID_KEYWORD "double")
	SYNTAX_ADD(SSID_KEYWORD "else")
	SYNTAX_ADD(SSID_KEYWORD "eval")
	SYNTAX_ADD(SSID_KEYWORD "final")
	SYNTAX_ADD(SSID_KEYWORD "finally")
	SYNTAX_ADD(SSID_KEYWORD "float")
	SYNTAX_ADD(SSID_KEYWORD "for")
	SYNTAX_ADD(SSID_KEYWORD "function")
	SYNTAX_ADD(SSID_KEYWORD "goto")
	SYNTAX_ADD(SSID_KEYWORD "implements")
	SYNTAX_ADD(SSID_KEYWORD "in")
	SYNTAX_ADD(SSID_KEYWORD "instanceof")
	SYNTAX_ADD(SSID_KEYWORD "int")
	SYNTAX_ADD(SSID_KEYWORD "interface")
	SYNTAX_ADD(SSID_KEYWORD "long")
	SYNTAX_ADD(SSID_KEYWORD "native")
	SYNTAX_ADD(SSID_KEYWORD "new")
	SYNTAX_ADD(SSID_KEYWORD "package")
	SYNTAX_ADD(SSID_KEYWORD "private")
	SYNTAX_ADD(SSID_KEYWORD "protected")
	SYNTAX_ADD(SSID_KEYWORD "public")
	SYNTAX_ADD(SSID_KEYWORD "return")
	SYNTAX_ADD(SSID_KEYWORD "short")
	SYNTAX_ADD(SSID_KEYWORD "static")
	SYNTAX_ADD(SSID_KEYWORD "switch")
	SYNTAX_ADD(SSID_KEYWORD "synchronized")
	SYNTAX_ADD(SSID_KEYWORD "this")
	SYNTAX_ADD(SSID_KEYWORD "throw")
	SYNTAX_ADD(SSID_KEYWORD "throws")
	SYNTAX_ADD(SSID_KEYWORD "transient")
	SYNTAX_ADD(SSID_KEYWORD "try")
	SYNTAX_ADD(SSID_KEYWORD "typeof")
	SYNTAX_ADD(SSID_KEYWORD "void")
	SYNTAX_ADD(SSID_KEYWORD "volatile")
	SYNTAX_ADD(SSID_KEYWORD "while")
	SYNTAX_ADD(SSID_KEYWORD "with")
	SYNTAX_ADD(SSID_KEYWORD "yield")
	SYNTAX_ADD(SSID_KEYWORD "import")
	SYNTAX_ADD(SSID_KEYWORD "export")
	SYNTAX_ADD(SSID_KEYWORD "from")
	SYNTAX_ADD(SSID_TYPE "let")
	SYNTAX_ADD(SSID_TYPE "var")
	SYNTAX_ADD(SSID_CONST "true")
	SYNTAX_ADD(SSID_CONST "false")
	SYNTAX_ADD(SSID_CONST "null")
	SYNTAX_ADD_RANGE(SSID_COMMENT "//", "\0")
	SYNTAX_ADD_RANGE(SSID_COMMENT "/*", "*/")
	SYNTAX_ADD_RANGE(SSID_STRING "\"", "\"")
	SYNTAX_ADD_RANGE(SSID_CHARACTER_LITERAL "'", "'")
	SYNTAX_ADD(SSID_OPERATOR "=")
	SYNTAX_ADD(SSID_OPERATOR "!")
	SYNTAX_ADD(SSID_OPERATOR "+")
	SYNTAX_ADD(SSID_OPERATOR "-")
	SYNTAX_ADD(SSID_OPERATOR "*")
	SYNTAX_ADD(SSID_OPERATOR "/")
	SYNTAX_ADD(SSID_OPERATOR "~")
	SYNTAX_ADD(SSID_OPERATOR "<")
	SYNTAX_ADD(SSID_OPERATOR ">")
	SYNTAX_ADD(SSID_OPERATOR "?")
	SYNTAX_ADD(SSID_OPERATOR ":")
	SYNTAX_ADD(SSID_OPERATOR "&")
	SYNTAX_ADD(SSID_OPERATOR "%")
	SYNTAX_ADD(SSID_OPERATOR "~")
	SYNTAX_ADD(SSID_OPERATOR "|")
	SYNTAX_ADD(SSID_OPERATOR "^")
SYNTAX_END(syntax_js)

SYNTAX_NEW(syntax_java)
	SYNTAX_EXT_COUNT(1)
	SYNTAX_ADD_EXT(".java")
	SYNTAX_ADD(SSID_KEYWORD "if")
	SYNTAX_ADD(SSID_KEYWORD "break")
	SYNTAX_ADD(SSID_KEYWORD "case")
	SYNTAX_ADD(SSID_KEYWORD "catch")
	SYNTAX_ADD(SSID_KEYWORD "continue")
	SYNTAX_ADD(SSID_KEYWORD "default")
	SYNTAX_ADD(SSID_KEYWORD "do")
	SYNTAX_ADD(SSID_KEYWORD "else")
	SYNTAX_ADD(SSID_KEYWORD "finally")
	SYNTAX_ADD(SSID_KEYWORD "for")
	SYNTAX_ADD(SSID_KEYWORD "instanceof")
	SYNTAX_ADD(SSID_KEYWORD "interface")
	SYNTAX_ADD(SSID_KEYWORD "new")
	SYNTAX_ADD(SSID_KEYWORD "return")
	SYNTAX_ADD(SSID_KEYWORD "switch")
	SYNTAX_ADD(SSID_KEYWORD "this")
	SYNTAX_ADD(SSID_KEYWORD "throw")
	SYNTAX_ADD(SSID_KEYWORD "try")
	SYNTAX_ADD(SSID_KEYWORD "while")
	SYNTAX_ADD(SSID_TYPE "void")
	SYNTAX_ADD(SSID_TYPE "byte")
	SYNTAX_ADD(SSID_TYPE "boolean")
	SYNTAX_ADD(SSID_TYPE "char")
	SYNTAX_ADD(SSID_TYPE "short")
	SYNTAX_ADD(SSID_TYPE "int")
	SYNTAX_ADD(SSID_TYPE "long")
	SYNTAX_ADD(SSID_TYPE "volatile")
	SYNTAX_ADD(SSID_TYPE "strictfp")
	SYNTAX_ADD(SSID_TYPE "public")
	SYNTAX_ADD(SSID_TYPE "private")
	SYNTAX_ADD(SSID_TYPE "protected")
	SYNTAX_ADD(SSID_TYPE "class")
	SYNTAX_ADD(SSID_TYPE "abstract")
	SYNTAX_ADD(SSID_TYPE "static")
	SYNTAX_ADD(SSID_TYPE "synchronized")
	SYNTAX_ADD(SSID_TYPE "throws")
	SYNTAX_ADD(SSID_CONST "true")
	SYNTAX_ADD(SSID_CONST "false")
	SYNTAX_ADD(SSID_CONST "null")
	SYNTAX_ADD(SSID_MACRO "import")
	SYNTAX_ADD(SSID_MACRO "native")
	SYNTAX_ADD(SSID_MACRO "package")
	SYNTAX_ADD_RANGE(SSID_COMMENT "//", "\0")
	SYNTAX_ADD_RANGE(SSID_COMMENT "/*", "*/")
	SYNTAX_ADD_RANGE(SSID_STRING "\"", "\"")
	SYNTAX_ADD_RANGE(SSID_CHARACTER_LITERAL "'", "'")
	SYNTAX_ADD(SSID_OPERATOR "=")
	SYNTAX_ADD(SSID_OPERATOR "!")
	SYNTAX_ADD(SSID_OPERATOR "+")
	SYNTAX_ADD(SSID_OPERATOR "-")
	SYNTAX_ADD(SSID_OPERATOR "*")
	SYNTAX_ADD(SSID_OPERATOR "/")
	SYNTAX_ADD(SSID_OPERATOR "~")
	SYNTAX_ADD(SSID_OPERATOR "<")
	SYNTAX_ADD(SSID_OPERATOR ">")
	SYNTAX_ADD(SSID_OPERATOR "?")
	SYNTAX_ADD(SSID_OPERATOR ":")
	SYNTAX_ADD(SSID_OPERATOR "&")
	SYNTAX_ADD(SSID_OPERATOR "%")
	SYNTAX_ADD(SSID_OPERATOR "~")
	SYNTAX_ADD(SSID_OPERATOR "|")
	SYNTAX_ADD(SSID_OPERATOR "^")
SYNTAX_END(syntax_java)

SYNTAX_NEW(syntax_css)
	SYNTAX_EXT_COUNT(1)
	SYNTAX_ADD_EXT(".css")
	SYNTAX_ADD(SSID_NUMBER "px")
	SYNTAX_ADD(SSID_TYPE "let:")
	SYNTAX_ADD(SSID_TYPE "var:")
	SYNTAX_ADD(SSID_TYPE "accelerator:")
	SYNTAX_ADD(SSID_TYPE "accesskey:")
	SYNTAX_ADD(SSID_TYPE ":active:")
	SYNTAX_ADD(SSID_TYPE "additive-symbols:")
	SYNTAX_ADD(SSID_TYPE "::after:")
	SYNTAX_ADD(SSID_TYPE "-ah-:")
	SYNTAX_ADD(SSID_TYPE "align-content:")
	SYNTAX_ADD(SSID_TYPE "align-items:")
	SYNTAX_ADD(SSID_TYPE "alignment-adjust:")
	SYNTAX_ADD(SSID_TYPE "alignment-baseline:")
	SYNTAX_ADD(SSID_TYPE "align-self:")
	SYNTAX_ADD(SSID_TYPE "all:")
	SYNTAX_ADD(SSID_TYPE "::alternate:")
	SYNTAX_ADD(SSID_TYPE "anchor-point:")
	SYNTAX_ADD(SSID_TYPE "<angle>:")
	SYNTAX_ADD(SSID_TYPE "animation:")
	SYNTAX_ADD(SSID_TYPE "animation-delay:")
	SYNTAX_ADD(SSID_TYPE "animation-direction:")
	SYNTAX_ADD(SSID_TYPE "animation-duration:")
	SYNTAX_ADD(SSID_TYPE "animation-fill-mode:")
	SYNTAX_ADD(SSID_TYPE "animation-iteration-count:")
	SYNTAX_ADD(SSID_TYPE "animation-name:")
	SYNTAX_ADD(SSID_TYPE "animation-play-state:")
	SYNTAX_ADD(SSID_TYPE "animation-timing-function:")
	SYNTAX_ADD(SSID_TYPE "::anonymous-block:")
	SYNTAX_ADD(SSID_TYPE "::anonymous-positioned-block:")
	SYNTAX_ADD(SSID_TYPE ":any():")
	SYNTAX_ADD(SSID_TYPE ":any-link:")
	SYNTAX_ADD(SSID_TYPE "appearance:")
	SYNTAX_ADD(SSID_TYPE "-apple-:")
	SYNTAX_ADD(SSID_TYPE "app-region:")
	SYNTAX_ADD(SSID_TYPE "aspect-ratio:")
	SYNTAX_ADD(SSID_TYPE "aspect-ratio @?:")
	SYNTAX_ADD(SSID_TYPE ":at-level:")
	SYNTAX_ADD(SSID_TYPE "-atsc-:")
	SYNTAX_ADD(SSID_TYPE "attr():")
	SYNTAX_ADD(SSID_TYPE "auto:")
	SYNTAX_ADD(SSID_TYPE "azimuth:")
	SYNTAX_ADD(SSID_TYPE "::backdrop:")
	SYNTAX_ADD(SSID_TYPE "backface-visibility:")
	SYNTAX_ADD(SSID_TYPE "background:")
	SYNTAX_ADD(SSID_TYPE "background-attachment:")
	SYNTAX_ADD(SSID_TYPE "background-clip:")
	SYNTAX_ADD(SSID_TYPE "background-color:")
	SYNTAX_ADD(SSID_TYPE "background-composite:")
	SYNTAX_ADD(SSID_TYPE "background-image:")
	SYNTAX_ADD(SSID_TYPE "background-inline-policy:")
	SYNTAX_ADD(SSID_TYPE "background-origin:")
	SYNTAX_ADD(SSID_TYPE "background-origin-x:")
	SYNTAX_ADD(SSID_TYPE "background-origin-y:")
	SYNTAX_ADD(SSID_TYPE "background-position:")
	SYNTAX_ADD(SSID_TYPE "background-position-x:")
	SYNTAX_ADD(SSID_TYPE "background-position-y:")
	SYNTAX_ADD(SSID_TYPE "background-repeat:")
	SYNTAX_ADD(SSID_TYPE "background-size:")
	SYNTAX_ADD(SSID_TYPE "baseline-shift:")
	SYNTAX_ADD(SSID_TYPE "::before:")
	SYNTAX_ADD(SSID_TYPE "behavior:")
	SYNTAX_ADD(SSID_TYPE ":below-level:")
	SYNTAX_ADD(SSID_TYPE "binding:")
	SYNTAX_ADD(SSID_TYPE ":blank:")
	SYNTAX_ADD(SSID_TYPE "bleed:")
	SYNTAX_ADD(SSID_TYPE "blend-mode:")
	SYNTAX_ADD(SSID_TYPE "block-progression:")
	SYNTAX_ADD(SSID_TYPE "bookmark-label:")
	SYNTAX_ADD(SSID_TYPE "bookmark-level:")
	SYNTAX_ADD(SSID_TYPE "bookmark-state:")
	SYNTAX_ADD(SSID_TYPE "bookmark-target:")
	SYNTAX_ADD(SSID_TYPE "border:")
	SYNTAX_ADD(SSID_TYPE "border-after:")
	SYNTAX_ADD(SSID_TYPE "border-after-color:")
	SYNTAX_ADD(SSID_TYPE "border-after-style:")
	SYNTAX_ADD(SSID_TYPE "border-after-width:")
	SYNTAX_ADD(SSID_TYPE "border-before:")
	SYNTAX_ADD(SSID_TYPE "border-before-color:")
	SYNTAX_ADD(SSID_TYPE "border-before-style:")
	SYNTAX_ADD(SSID_TYPE "border-before-width:")
	SYNTAX_ADD(SSID_TYPE "border-bottom:")
	SYNTAX_ADD(SSID_TYPE "border-bottom-color:")
	SYNTAX_ADD(SSID_TYPE "border-bottom-colors:")
	SYNTAX_ADD(SSID_TYPE "border-bottom-left-radius:")
	SYNTAX_ADD(SSID_TYPE "border-bottom-right-radius:")
	SYNTAX_ADD(SSID_TYPE "border-bottom-style:")
	SYNTAX_ADD(SSID_TYPE "border-bottom-width:")
	SYNTAX_ADD(SSID_TYPE "border-clip:")
	SYNTAX_ADD(SSID_TYPE "border-clip-bottom:")
	SYNTAX_ADD(SSID_TYPE "border-clip-left:")
	SYNTAX_ADD(SSID_TYPE "border-clip-right:")
	SYNTAX_ADD(SSID_TYPE "border-clip-top:")
	SYNTAX_ADD(SSID_TYPE "border-collapse:")
	SYNTAX_ADD(SSID_TYPE "border-color:")
	SYNTAX_ADD(SSID_TYPE "border-end:")
	SYNTAX_ADD(SSID_TYPE "border-end-color:")
	SYNTAX_ADD(SSID_TYPE "border-end-style:")
	SYNTAX_ADD(SSID_TYPE "border-end-width:")
	SYNTAX_ADD(SSID_TYPE "border-fit:")
	SYNTAX_ADD(SSID_TYPE "border-horizontal-spacing:")
	SYNTAX_ADD(SSID_TYPE "border-image:")
	SYNTAX_ADD(SSID_TYPE "border-image-outset:")
	SYNTAX_ADD(SSID_TYPE "border-image-repeat:")
	SYNTAX_ADD(SSID_TYPE "border-image-slice:")
	SYNTAX_ADD(SSID_TYPE "border-image-source:")
	SYNTAX_ADD(SSID_TYPE "border-image-width:")
	SYNTAX_ADD(SSID_TYPE "border-left:")
	SYNTAX_ADD(SSID_TYPE "border-left-colors:")
	SYNTAX_ADD(SSID_TYPE "border-left-color:")
	SYNTAX_ADD(SSID_TYPE "border-left-style:")
	SYNTAX_ADD(SSID_TYPE "border-left-width:")
	SYNTAX_ADD(SSID_TYPE "border-radius:")
	SYNTAX_ADD(SSID_TYPE "border-right:")
	SYNTAX_ADD(SSID_TYPE "border-right-color:")
	SYNTAX_ADD(SSID_TYPE "border-right-colors:")
	SYNTAX_ADD(SSID_TYPE "border-right-style:")
	SYNTAX_ADD(SSID_TYPE "border-right-width:")
	SYNTAX_ADD(SSID_TYPE "border-spacing:")
	SYNTAX_ADD(SSID_TYPE "border-start:")
	SYNTAX_ADD(SSID_TYPE "border-start-color:")
	SYNTAX_ADD(SSID_TYPE "border-start-style:")
	SYNTAX_ADD(SSID_TYPE "border-start-width:")
	SYNTAX_ADD(SSID_TYPE "border-style:")
	SYNTAX_ADD(SSID_TYPE "border-top:")
	SYNTAX_ADD(SSID_TYPE "border-top-color:")
	SYNTAX_ADD(SSID_TYPE "border-top-colors:")
	SYNTAX_ADD(SSID_TYPE "border-top-left-radius:")
	SYNTAX_ADD(SSID_TYPE "border-top-right-radius:")
	SYNTAX_ADD(SSID_TYPE "border-top-style:")
	SYNTAX_ADD(SSID_TYPE "border-top-width:")
	SYNTAX_ADD(SSID_TYPE "border-vertical-spacing:")
	SYNTAX_ADD(SSID_TYPE "border-width:")
	SYNTAX_ADD(SSID_TYPE "bottom:")
	SYNTAX_ADD(SSID_TYPE ":bound-element:")
	SYNTAX_ADD(SSID_TYPE "box-align:")
	SYNTAX_ADD(SSID_TYPE "box-decoration-break:")
	SYNTAX_ADD(SSID_TYPE "box-direction:")
	SYNTAX_ADD(SSID_TYPE "box-flex:")
	SYNTAX_ADD(SSID_TYPE "box-flex-group:")
	SYNTAX_ADD(SSID_TYPE "box-lines:")
	SYNTAX_ADD(SSID_TYPE "box-ordinal-group:")
	SYNTAX_ADD(SSID_TYPE "box-orient:")
	SYNTAX_ADD(SSID_TYPE "box-pack:")
	SYNTAX_ADD(SSID_TYPE "box-reflect:")
	SYNTAX_ADD(SSID_TYPE "box-shadow:")
	SYNTAX_ADD(SSID_TYPE "box-sizing:")
	SYNTAX_ADD(SSID_TYPE "box-snap:")
	SYNTAX_ADD(SSID_TYPE "break-after:")
	SYNTAX_ADD(SSID_TYPE "break-before:")
	SYNTAX_ADD(SSID_TYPE "break-inside:")
	SYNTAX_ADD(SSID_TYPE ":broken:")
	SYNTAX_ADD(SSID_TYPE "::browse:")
	SYNTAX_ADD(SSID_TYPE "calc():")
	SYNTAX_ADD(SSID_TYPE "::canvas:")
	SYNTAX_ADD(SSID_TYPE "canvas():")
	SYNTAX_ADD(SSID_TYPE "caption-side:")
	SYNTAX_ADD(SSID_TYPE "::cell-content:")
	SYNTAX_ADD(SSID_TYPE "ch:")
	SYNTAX_ADD(SSID_TYPE "chains:")
	SYNTAX_ADD(SSID_TYPE "@charset:")
	SYNTAX_ADD(SSID_TYPE "::check:")
	SYNTAX_ADD(SSID_TYPE ":checked:")
	SYNTAX_ADD(SSID_TYPE "::choices:")
	SYNTAX_ADD(SSID_TYPE "clear:")
	SYNTAX_ADD(SSID_TYPE "::clear:")
	SYNTAX_ADD(SSID_TYPE "clip:")
	SYNTAX_ADD(SSID_TYPE "clip-path:")
	SYNTAX_ADD(SSID_TYPE "clip-rule:")
	SYNTAX_ADD(SSID_TYPE "cm:")
	SYNTAX_ADD(SSID_TYPE "color:")
	SYNTAX_ADD(SSID_TYPE "color @?:")
	SYNTAX_ADD(SSID_TYPE "<color>:")
	SYNTAX_ADD(SSID_TYPE "color-correction:")
	SYNTAX_ADD(SSID_TYPE "color-index @?:")
	SYNTAX_ADD(SSID_TYPE "color-profile:")
	SYNTAX_ADD(SSID_TYPE "@color-profile:")
	SYNTAX_ADD(SSID_TYPE "::column():")
	SYNTAX_ADD(SSID_TYPE "column-axis:")
	SYNTAX_ADD(SSID_TYPE "column-break-after:")
	SYNTAX_ADD(SSID_TYPE "column-break-before:")
	SYNTAX_ADD(SSID_TYPE "column-break-inside:")
	SYNTAX_ADD(SSID_TYPE "column-count:")
	SYNTAX_ADD(SSID_TYPE "column-fill:")
	SYNTAX_ADD(SSID_TYPE "column-gap:")
	SYNTAX_ADD(SSID_TYPE "column-progression:")
	SYNTAX_ADD(SSID_TYPE "column-rule:")
	SYNTAX_ADD(SSID_TYPE "column-rule-color:")
	SYNTAX_ADD(SSID_TYPE "column-rule-style:")
	SYNTAX_ADD(SSID_TYPE "column-rule-width:")
	SYNTAX_ADD(SSID_TYPE "columns:")
	SYNTAX_ADD(SSID_TYPE "column-span:")
	SYNTAX_ADD(SSID_TYPE "column-width:")
	SYNTAX_ADD(SSID_TYPE ":contains():")
	SYNTAX_ADD(SSID_TYPE "content:")
	SYNTAX_ADD(SSID_TYPE "content-zoom-chaining:")
	SYNTAX_ADD(SSID_TYPE "content-zooming:")
	SYNTAX_ADD(SSID_TYPE "content-zoom-limit:")
	SYNTAX_ADD(SSID_TYPE "content-zoom-limit-max:")
	SYNTAX_ADD(SSID_TYPE "content-zoom-limit-min:")
	SYNTAX_ADD(SSID_TYPE "content-zoom-snap:")
	SYNTAX_ADD(SSID_TYPE "content-zoom-snap-points:")
	SYNTAX_ADD(SSID_TYPE "content-zoom-snap-type:")
	SYNTAX_ADD(SSID_TYPE "@counter:")
	SYNTAX_ADD(SSID_TYPE "counter():")
	SYNTAX_ADD(SSID_TYPE "counter-increment:")
	SYNTAX_ADD(SSID_TYPE "counter-reset:")
	SYNTAX_ADD(SSID_TYPE "counters():")
	SYNTAX_ADD(SSID_TYPE "@counter-style:")
	SYNTAX_ADD(SSID_TYPE "crop:")
	SYNTAX_ADD(SSID_TYPE "cross-fade():")
	SYNTAX_ADD(SSID_TYPE "cubic-bezier():")
	SYNTAX_ADD(SSID_TYPE "cue:")
	SYNTAX_ADD(SSID_TYPE "cue-after:")
	SYNTAX_ADD(SSID_TYPE "cue-before:")
	SYNTAX_ADD(SSID_TYPE ":current:")
	SYNTAX_ADD(SSID_TYPE "cursor:")
	SYNTAX_ADD(SSID_TYPE "cycle():")
	SYNTAX_ADD(SSID_TYPE "dashboard-region:")
	SYNTAX_ADD(SSID_TYPE "default:")
	SYNTAX_ADD(SSID_TYPE ":default:")
	SYNTAX_ADD(SSID_TYPE "deg:")
	SYNTAX_ADD(SSID_TYPE "device-aspect-ratio @?:")
	SYNTAX_ADD(SSID_TYPE "device-cmyk():")
	SYNTAX_ADD(SSID_TYPE "device-pixel-ratio @?:")
	SYNTAX_ADD(SSID_TYPE "device-width @?:")
	SYNTAX_ADD(SSID_TYPE ":dir():")
	SYNTAX_ADD(SSID_TYPE "direction:")
	SYNTAX_ADD(SSID_TYPE ":disabled:")
	SYNTAX_ADD(SSID_TYPE "display:")
	SYNTAX_ADD(SSID_TYPE "display-box:")
	SYNTAX_ADD(SSID_TYPE "display-extras:")
	SYNTAX_ADD(SSID_TYPE "display-inside:")
	SYNTAX_ADD(SSID_TYPE "display-outside:")
	SYNTAX_ADD(SSID_TYPE "@document:")
	SYNTAX_ADD(SSID_TYPE "dominant-baseline:")
	SYNTAX_ADD(SSID_TYPE "dpcm:")
	SYNTAX_ADD(SSID_TYPE "dpi:")
	SYNTAX_ADD(SSID_TYPE "dppx:")
	SYNTAX_ADD(SSID_TYPE ":drag-over:")
	SYNTAX_ADD(SSID_TYPE "drop-initial-after-adjust:")
	SYNTAX_ADD(SSID_TYPE "drop-initial-after-align:")
	SYNTAX_ADD(SSID_TYPE "drop-initial-before-adjust:")
	SYNTAX_ADD(SSID_TYPE "drop-initial-before-align:")
	SYNTAX_ADD(SSID_TYPE "drop-initial-size:")
	SYNTAX_ADD(SSID_TYPE "drop-initial-value:")
	SYNTAX_ADD(SSID_TYPE "element():")
	SYNTAX_ADD(SSID_TYPE "elevation:")
	SYNTAX_ADD(SSID_TYPE "em:")
	SYNTAX_ADD(SSID_TYPE ":empty:")
	SYNTAX_ADD(SSID_TYPE "empty-cells:")
	SYNTAX_ADD(SSID_TYPE ":enabled:")
	SYNTAX_ADD(SSID_TYPE "-epub-:")
	SYNTAX_ADD(SSID_TYPE "ex:")
	SYNTAX_ADD(SSID_TYPE "::expand:")
	SYNTAX_ADD(SSID_TYPE "expression():")
	SYNTAX_ADD(SSID_TYPE "fallback:")
	SYNTAX_ADD(SSID_TYPE "fill:")
	SYNTAX_ADD(SSID_TYPE "::fill:")
	SYNTAX_ADD(SSID_TYPE "::fill-lower:")
	SYNTAX_ADD(SSID_TYPE "fill-opacity:")
	SYNTAX_ADD(SSID_TYPE "fill-rule:")
	SYNTAX_ADD(SSID_TYPE "::fill-upper:")
	SYNTAX_ADD(SSID_TYPE "filter:")
	SYNTAX_ADD(SSID_TYPE ":first:")
	SYNTAX_ADD(SSID_TYPE ":first-child:")
	SYNTAX_ADD(SSID_TYPE "::first-letter:")
	SYNTAX_ADD(SSID_TYPE "::first-line:")
	SYNTAX_ADD(SSID_TYPE ":first-node:")
	SYNTAX_ADD(SSID_TYPE ":first-of-type:")
	SYNTAX_ADD(SSID_TYPE "::first-page:")
	SYNTAX_ADD(SSID_TYPE "fit:")
	SYNTAX_ADD(SSID_TYPE "fit-position:")
	SYNTAX_ADD(SSID_TYPE "flavor:")
	SYNTAX_ADD(SSID_TYPE "flex:")
	SYNTAX_ADD(SSID_TYPE "flex:")
	SYNTAX_ADD(SSID_TYPE "flex-align:")
	SYNTAX_ADD(SSID_TYPE "flex-basis:")
	SYNTAX_ADD(SSID_TYPE "flex-direction:")
	SYNTAX_ADD(SSID_TYPE "flex-flow:")
	SYNTAX_ADD(SSID_TYPE "flex-grow:")
	SYNTAX_ADD(SSID_TYPE "flex-order:")
	SYNTAX_ADD(SSID_TYPE "flex-pack:")
	SYNTAX_ADD(SSID_TYPE "flex-shrink:")
	SYNTAX_ADD(SSID_TYPE "flex-wrap:")
	SYNTAX_ADD(SSID_TYPE "float:")
	SYNTAX_ADD(SSID_TYPE "float-edge:")
	SYNTAX_ADD(SSID_TYPE "float-offset:")
	SYNTAX_ADD(SSID_TYPE "flood-color:")
	SYNTAX_ADD(SSID_TYPE "flood-opacity:")
	SYNTAX_ADD(SSID_TYPE "flow-from:")
	SYNTAX_ADD(SSID_TYPE "flow-into:")
	SYNTAX_ADD(SSID_TYPE ":focus:")
	SYNTAX_ADD(SSID_TYPE ":focus-inner:")
	SYNTAX_ADD(SSID_TYPE "focus-opacity:")
	SYNTAX_ADD(SSID_TYPE ":focus-outer:")
	SYNTAX_ADD(SSID_TYPE ":focusring:")
	SYNTAX_ADD(SSID_TYPE "font:")
	SYNTAX_ADD(SSID_TYPE "font-color:")
	SYNTAX_ADD(SSID_TYPE "font-emphasize:")
	SYNTAX_ADD(SSID_TYPE "font-emphasize-position:")
	SYNTAX_ADD(SSID_TYPE "font-emphasize-style:")
	SYNTAX_ADD(SSID_TYPE "@font-face:")
	SYNTAX_ADD(SSID_TYPE "font-family:")
	SYNTAX_ADD(SSID_TYPE "font-feature-settings:")
	SYNTAX_ADD(SSID_TYPE "@font-feature-values:")
	SYNTAX_ADD(SSID_TYPE "font-kerning:")
	SYNTAX_ADD(SSID_TYPE "font-language-override:")
	SYNTAX_ADD(SSID_TYPE "font-size:")
	SYNTAX_ADD(SSID_TYPE "font-size-adjust:")
	SYNTAX_ADD(SSID_TYPE "font-size-delta:")
	SYNTAX_ADD(SSID_TYPE "font-smooth:")
	SYNTAX_ADD(SSID_TYPE "font-smoothing:")
	SYNTAX_ADD(SSID_TYPE "font-stretch:")
	SYNTAX_ADD(SSID_TYPE "font-style:")
	SYNTAX_ADD(SSID_TYPE "font-synthesis:")
	SYNTAX_ADD(SSID_TYPE "font-variant:")
	SYNTAX_ADD(SSID_TYPE "font-variant-alternates:")
	SYNTAX_ADD(SSID_TYPE "font-variant-caps:")
	SYNTAX_ADD(SSID_TYPE "font-variant-east-asian:")
	SYNTAX_ADD(SSID_TYPE "font-variant-ligatures:")
	SYNTAX_ADD(SSID_TYPE "font-variant-numeric:")
	SYNTAX_ADD(SSID_TYPE "font-variant-position:")
	SYNTAX_ADD(SSID_TYPE "font-weight:")
	SYNTAX_ADD(SSID_TYPE "footnote:")
	SYNTAX_ADD(SSID_TYPE "::footnote-call:")
	SYNTAX_ADD(SSID_TYPE "::footnote-marker:")
	SYNTAX_ADD(SSID_TYPE "force-broken-image-icon:")
	SYNTAX_ADD(SSID_TYPE "fr:")
	SYNTAX_ADD(SSID_TYPE "<frequency>:")
	SYNTAX_ADD(SSID_TYPE ":fullscreen:")
	SYNTAX_ADD(SSID_TYPE ":full-screen:")
	SYNTAX_ADD(SSID_TYPE ":full-screen-ancestor:")
	SYNTAX_ADD(SSID_TYPE ":future:")
	SYNTAX_ADD(SSID_TYPE "gd:")
	SYNTAX_ADD(SSID_TYPE "glyph-orientation-horizontal:")
	SYNTAX_ADD(SSID_TYPE "glyph-orientation-vertical:")
	SYNTAX_ADD(SSID_TYPE "grad:")
	SYNTAX_ADD(SSID_TYPE "<gradient>:")
	SYNTAX_ADD(SSID_TYPE "grid @?:")
	SYNTAX_ADD(SSID_TYPE "grid-area:")
	SYNTAX_ADD(SSID_TYPE "grid-auto-columns:")
	SYNTAX_ADD(SSID_TYPE "grid-auto-flow:")
	SYNTAX_ADD(SSID_TYPE "grid-auto-rows:")
	SYNTAX_ADD(SSID_TYPE "grid-column:")
	SYNTAX_ADD(SSID_TYPE "grid-column-align:")
	SYNTAX_ADD(SSID_TYPE "grid-column-position:")
	SYNTAX_ADD(SSID_TYPE "grid-columns:")
	SYNTAX_ADD(SSID_TYPE "grid-column-span:")
	SYNTAX_ADD(SSID_TYPE "grid-definition-columns:")
	SYNTAX_ADD(SSID_TYPE "grid-definition-rows:")
	SYNTAX_ADD(SSID_TYPE "grid-position:")
	SYNTAX_ADD(SSID_TYPE "grid-row:")
	SYNTAX_ADD(SSID_TYPE "grid-row-align:")
	SYNTAX_ADD(SSID_TYPE "grid-row-position:")
	SYNTAX_ADD(SSID_TYPE "grid-rows:")
	SYNTAX_ADD(SSID_TYPE "grid-row-span:")
	SYNTAX_ADD(SSID_TYPE "grid-span:")
	SYNTAX_ADD(SSID_TYPE "grid-template:")
	SYNTAX_ADD(SSID_TYPE ":handler-blocked:")
	SYNTAX_ADD(SSID_TYPE ":handler-crashed:")
	SYNTAX_ADD(SSID_TYPE ":handler-disabled:")
	SYNTAX_ADD(SSID_TYPE "hanging-punctuation:")
	SYNTAX_ADD(SSID_TYPE "height:")
	SYNTAX_ADD(SSID_TYPE "height @?:")
	SYNTAX_ADD(SSID_TYPE "high-contrast @?:")
	SYNTAX_ADD(SSID_TYPE "high-contrast-adjust:")
	SYNTAX_ADD(SSID_TYPE "highlight:")
	SYNTAX_ADD(SSID_TYPE "horiz-align:")
	SYNTAX_ADD(SSID_TYPE ":hover:")
	SYNTAX_ADD(SSID_TYPE "-hp-:")
	SYNTAX_ADD(SSID_TYPE "hsl():")
	SYNTAX_ADD(SSID_TYPE "hsla():")
	SYNTAX_ADD(SSID_TYPE "hyphenate-character:")
	SYNTAX_ADD(SSID_TYPE "hyphenate-limit-after:")
	SYNTAX_ADD(SSID_TYPE "hyphenate-limit-before:")
	SYNTAX_ADD(SSID_TYPE "hyphenate-limit-chars:")
	SYNTAX_ADD(SSID_TYPE "hyphenate-limit-last:")
	SYNTAX_ADD(SSID_TYPE "hyphenate-limit-lines:")
	SYNTAX_ADD(SSID_TYPE "hyphenate-limit-zone:")
	SYNTAX_ADD(SSID_TYPE "hyphenate-resource:")
	SYNTAX_ADD(SSID_TYPE "hyphens:")
	SYNTAX_ADD(SSID_TYPE "Hz:")
	SYNTAX_ADD(SSID_TYPE "icon:")
	SYNTAX_ADD(SSID_TYPE "image():")
	SYNTAX_ADD(SSID_TYPE "<image>:")
	SYNTAX_ADD(SSID_TYPE "image-orientation:")
	SYNTAX_ADD(SSID_TYPE "image-rect():")
	SYNTAX_ADD(SSID_TYPE "image-region():")
	SYNTAX_ADD(SSID_TYPE "image-rendering:")
	SYNTAX_ADD(SSID_TYPE "image-resolution:")
	SYNTAX_ADD(SSID_TYPE "image-orientation:")
	SYNTAX_ADD(SSID_TYPE "images-in-menus @?:")
	SYNTAX_ADD(SSID_TYPE "ime-mode:")
	SYNTAX_ADD(SSID_TYPE "@import:")
	SYNTAX_ADD(SSID_TYPE "!important:")
	SYNTAX_ADD(SSID_TYPE "in:")
	SYNTAX_ADD(SSID_TYPE "include-source:")
	SYNTAX_ADD(SSID_TYPE ":indeterminate:")
	SYNTAX_ADD(SSID_TYPE "inherit:")
	SYNTAX_ADD(SSID_TYPE "initial:")
	SYNTAX_ADD(SSID_TYPE "inline-box-align:")
	SYNTAX_ADD(SSID_TYPE "inline-flex:")
	SYNTAX_ADD(SSID_TYPE "inline-table:")
	SYNTAX_ADD(SSID_TYPE "::inline-table:")
	SYNTAX_ADD(SSID_TYPE "input-format:")
	SYNTAX_ADD(SSID_TYPE ":input-placeholder:")
	SYNTAX_ADD(SSID_TYPE "::input-placeholder:")
	SYNTAX_ADD(SSID_TYPE "input-required:")
	SYNTAX_ADD(SSID_TYPE ":in-range:")
	SYNTAX_ADD(SSID_TYPE "<integer>:")
	SYNTAX_ADD(SSID_TYPE "interpolation-mode:")
	SYNTAX_ADD(SSID_TYPE "interpret-as:")
	SYNTAX_ADD(SSID_TYPE ":invalid:")
	SYNTAX_ADD(SSID_TYPE "justify-items:")
	SYNTAX_ADD(SSID_TYPE "justify-content:")
	SYNTAX_ADD(SSID_TYPE "justify-self:")
	SYNTAX_ADD(SSID_TYPE "kerning:")
	SYNTAX_ADD(SSID_TYPE ":keyboard-active:")
	SYNTAX_ADD(SSID_TYPE "@keyframes:")
	SYNTAX_ADD(SSID_TYPE "-khtml-:")
	SYNTAX_ADD(SSID_TYPE "kHz:")
	SYNTAX_ADD(SSID_TYPE ":lang():")
	SYNTAX_ADD(SSID_TYPE "languages:")
	SYNTAX_ADD(SSID_TYPE ":last-child:")
	SYNTAX_ADD(SSID_TYPE ":last-of-type:")
	SYNTAX_ADD(SSID_TYPE ":last-node:")
	SYNTAX_ADD(SSID_TYPE "layout-flow:")
	SYNTAX_ADD(SSID_TYPE "layout-grid:")
	SYNTAX_ADD(SSID_TYPE "layout-grid-char:")
	SYNTAX_ADD(SSID_TYPE "layout-grid-char-spacing:")
	SYNTAX_ADD(SSID_TYPE "layout-grid-line:")
	SYNTAX_ADD(SSID_TYPE "layout-grid-mode:")
	SYNTAX_ADD(SSID_TYPE "layout-grid-type:")
	SYNTAX_ADD(SSID_TYPE "leader():")
	SYNTAX_ADD(SSID_TYPE "left:")
	SYNTAX_ADD(SSID_TYPE ":left:")
	SYNTAX_ADD(SSID_TYPE "<length>:")
	SYNTAX_ADD(SSID_TYPE "letter-spacing:")
	SYNTAX_ADD(SSID_TYPE "lighting-color:")
	SYNTAX_ADD(SSID_TYPE "line-align:")
	SYNTAX_ADD(SSID_TYPE "linear-gradient:")
	SYNTAX_ADD(SSID_TYPE "line-box-contain:")
	SYNTAX_ADD(SSID_TYPE "line-break:")
	SYNTAX_ADD(SSID_TYPE "line-clamp:")
	SYNTAX_ADD(SSID_TYPE "line-grid:")
	SYNTAX_ADD(SSID_TYPE "line-height:")
	SYNTAX_ADD(SSID_TYPE "::line-marker:")
	SYNTAX_ADD(SSID_TYPE "line-slack:")
	SYNTAX_ADD(SSID_TYPE "line-snap:")
	SYNTAX_ADD(SSID_TYPE "line-stacking:")
	SYNTAX_ADD(SSID_TYPE "line-stacking-ruby:")
	SYNTAX_ADD(SSID_TYPE "line-stacking-shift:")
	SYNTAX_ADD(SSID_TYPE "line-stacking-strategy:")
	SYNTAX_ADD(SSID_TYPE "link:")
	SYNTAX_ADD(SSID_TYPE ":link:")
	SYNTAX_ADD(SSID_TYPE "link-source:")
	SYNTAX_ADD(SSID_TYPE "::list-bullet:")
	SYNTAX_ADD(SSID_TYPE "list-image-1:")
	SYNTAX_ADD(SSID_TYPE "list-image-2:")
	SYNTAX_ADD(SSID_TYPE "list-image-3:")
	SYNTAX_ADD(SSID_TYPE "::list-number:")
	SYNTAX_ADD(SSID_TYPE "list-style-image:")
	SYNTAX_ADD(SSID_TYPE "list-style-position:")
	SYNTAX_ADD(SSID_TYPE "list-style-type:")
	SYNTAX_ADD(SSID_TYPE ":loading:")
	SYNTAX_ADD(SSID_TYPE "locale:")
	SYNTAX_ADD(SSID_TYPE ":locale-dir():")
	SYNTAX_ADD(SSID_TYPE ":local-link:")
	SYNTAX_ADD(SSID_TYPE "logical-height:")
	SYNTAX_ADD(SSID_TYPE "logical-width:")
	SYNTAX_ADD(SSID_TYPE ":lwtheme:")
	SYNTAX_ADD(SSID_TYPE ":lwtheme-darktext:")
	SYNTAX_ADD(SSID_TYPE "mac-graphite-theme @?:")
	SYNTAX_ADD(SSID_TYPE "maemo-classic:")
	SYNTAX_ADD(SSID_TYPE "margin:")
	SYNTAX_ADD(SSID_TYPE "margin-after:")
	SYNTAX_ADD(SSID_TYPE "margin-after-collapse:")
	SYNTAX_ADD(SSID_TYPE "margin-before:")
	SYNTAX_ADD(SSID_TYPE "margin-before-collapse:")
	SYNTAX_ADD(SSID_TYPE "margin-bottom:")
	SYNTAX_ADD(SSID_TYPE "margin-bottom-collapse:")
	SYNTAX_ADD(SSID_TYPE "margin-collapse:")
	SYNTAX_ADD(SSID_TYPE "margin-end:")
	SYNTAX_ADD(SSID_TYPE "margin-left:")
	SYNTAX_ADD(SSID_TYPE "margin-right:")
	SYNTAX_ADD(SSID_TYPE "margin-start:")
	SYNTAX_ADD(SSID_TYPE "margin-top:")
	SYNTAX_ADD(SSID_TYPE "margin-top-collapse:")
	SYNTAX_ADD(SSID_TYPE "marker:")
	SYNTAX_ADD(SSID_TYPE "::marker:")
	SYNTAX_ADD(SSID_TYPE "marker-end:")
	SYNTAX_ADD(SSID_TYPE "marker-mid:")
	SYNTAX_ADD(SSID_TYPE "marker-start:")
	SYNTAX_ADD(SSID_TYPE "marks:")
	SYNTAX_ADD(SSID_TYPE "marquee:")
	SYNTAX_ADD(SSID_TYPE "marquee:")
	SYNTAX_ADD(SSID_TYPE "marquee-dir:")
	SYNTAX_ADD(SSID_TYPE "marquee-direction:")
	SYNTAX_ADD(SSID_TYPE "marquee-increment:")
	SYNTAX_ADD(SSID_TYPE "marquee-loop:")
	SYNTAX_ADD(SSID_TYPE "marquee-play-count:")
	SYNTAX_ADD(SSID_TYPE "marquee-repetition:")
	SYNTAX_ADD(SSID_TYPE "marquee-speed:")
	SYNTAX_ADD(SSID_TYPE "marquee-style:")
	SYNTAX_ADD(SSID_TYPE "mask:")
	SYNTAX_ADD(SSID_TYPE "mask-attachment:")
	SYNTAX_ADD(SSID_TYPE "mask-box-image:")
	SYNTAX_ADD(SSID_TYPE "mask-box-image-outset:")
	SYNTAX_ADD(SSID_TYPE "mask-box-image-repeat:")
	SYNTAX_ADD(SSID_TYPE "mask-box-image-slice:")
	SYNTAX_ADD(SSID_TYPE "mask-box-image-source:")
	SYNTAX_ADD(SSID_TYPE "mask-box-image-width:")
	SYNTAX_ADD(SSID_TYPE "mask-clip:")
	SYNTAX_ADD(SSID_TYPE "mask-composite:")
	SYNTAX_ADD(SSID_TYPE "mask-image:")
	SYNTAX_ADD(SSID_TYPE "mask-origin:")
	SYNTAX_ADD(SSID_TYPE "mask-position:")
	SYNTAX_ADD(SSID_TYPE "mask-position-x:")
	SYNTAX_ADD(SSID_TYPE "mask-position-y:")
	SYNTAX_ADD(SSID_TYPE "mask-repeat:")
	SYNTAX_ADD(SSID_TYPE "mask-repeat-x:")
	SYNTAX_ADD(SSID_TYPE "mask-repeat-y:")
	SYNTAX_ADD(SSID_TYPE "mask-size:")
	SYNTAX_ADD(SSID_TYPE "mask-type:")
	SYNTAX_ADD(SSID_TYPE ":matches():")
	SYNTAX_ADD(SSID_TYPE "match-nearest-mail-blockquote-color:")
	SYNTAX_ADD(SSID_TYPE ":math-anonymous:")
	SYNTAX_ADD(SSID_TYPE ":math-columnline:")
	SYNTAX_ADD(SSID_TYPE ":math-firstcolumn:")
	SYNTAX_ADD(SSID_TYPE ":math-firstrow:")
	SYNTAX_ADD(SSID_TYPE ":math-font-size:")
	SYNTAX_ADD(SSID_TYPE ":math-font-style:")
	SYNTAX_ADD(SSID_TYPE ":math-lastcolumn:")
	SYNTAX_ADD(SSID_TYPE ":math-rowline:")
	SYNTAX_ADD(SSID_TYPE ":math-lastrow:")
	SYNTAX_ADD(SSID_TYPE ":math-stretchy:")
	SYNTAX_ADD(SSID_TYPE "max-color-index @?:")
	SYNTAX_ADD(SSID_TYPE "max-color @?:")
	SYNTAX_ADD(SSID_TYPE "max-device-aspect-ratio @?:")
	SYNTAX_ADD(SSID_TYPE "max-device-height @?:")
	SYNTAX_ADD(SSID_TYPE "max-device-pixel-ratio @?:")
	SYNTAX_ADD(SSID_TYPE "max-device-width @?:")
	SYNTAX_ADD(SSID_TYPE "max-height:")
	SYNTAX_ADD(SSID_TYPE "max-height @?:")
	SYNTAX_ADD(SSID_TYPE "max-logical-height:")
	SYNTAX_ADD(SSID_TYPE "max-logical-width:")
	SYNTAX_ADD(SSID_TYPE "max-monochrome @?:")
	SYNTAX_ADD(SSID_TYPE "max-resolution @?:")
	SYNTAX_ADD(SSID_TYPE "max-width:")
	SYNTAX_ADD(SSID_TYPE "max-width @?:")
	SYNTAX_ADD(SSID_TYPE "max-zoom:")
	SYNTAX_ADD(SSID_TYPE "@media:")
	SYNTAX_ADD(SSID_TYPE "min-aspect-ratio @?:")
	SYNTAX_ADD(SSID_TYPE "min-color @?:")
	SYNTAX_ADD(SSID_TYPE "min-color-index @?:")
	SYNTAX_ADD(SSID_TYPE "min-device-aspect-ratio @?:")
	SYNTAX_ADD(SSID_TYPE "min-device-height @?:")
	SYNTAX_ADD(SSID_TYPE "min-device-pixel-ratio @?:")
	SYNTAX_ADD(SSID_TYPE "min-device-width @?:")
	SYNTAX_ADD(SSID_TYPE "min-height:")
	SYNTAX_ADD(SSID_TYPE "min-height @?:")
	SYNTAX_ADD(SSID_TYPE "mini-fold:")
	SYNTAX_ADD(SSID_TYPE "min-logical-height:")
	SYNTAX_ADD(SSID_TYPE "min-logical-width:")
	SYNTAX_ADD(SSID_TYPE "minmax():")
	SYNTAX_ADD(SSID_TYPE "min-monochrome @?:")
	SYNTAX_ADD(SSID_TYPE "min-resolution @?:")
	SYNTAX_ADD(SSID_TYPE "min-width:")
	SYNTAX_ADD(SSID_TYPE "min-width @?:")
	SYNTAX_ADD(SSID_TYPE "min-zoom:")
	SYNTAX_ADD(SSID_TYPE "mm:")
	SYNTAX_ADD(SSID_TYPE "monochrome @?:")
	SYNTAX_ADD(SSID_TYPE "move-to:")
	SYNTAX_ADD(SSID_TYPE "-moz-:")
	SYNTAX_ADD(SSID_TYPE "-ms-:")
	SYNTAX_ADD(SSID_TYPE "ms:")
	SYNTAX_ADD(SSID_TYPE "mso-*:")
	SYNTAX_ADD(SSID_TYPE "@namespace:")
	SYNTAX_ADD(SSID_TYPE "nav-banner-image:")
	SYNTAX_ADD(SSID_TYPE "nav-bottom:")
	SYNTAX_ADD(SSID_TYPE "navbutton-*:")
	SYNTAX_ADD(SSID_TYPE "nav-down:")
	SYNTAX_ADD(SSID_TYPE "nav-down-shift:")
	SYNTAX_ADD(SSID_TYPE "@navigation:")
	SYNTAX_ADD(SSID_TYPE "nav-index:")
	SYNTAX_ADD(SSID_TYPE "nav-left:")
	SYNTAX_ADD(SSID_TYPE "nav-left-shift:")
	SYNTAX_ADD(SSID_TYPE "nav-right:")
	SYNTAX_ADD(SSID_TYPE "nav-right-shift:")
	SYNTAX_ADD(SSID_TYPE "nav-up:")
	SYNTAX_ADD(SSID_TYPE "nav-up-shift:")
	SYNTAX_ADD(SSID_TYPE "nbsp-mode:")
	SYNTAX_ADD(SSID_TYPE "negative:")
	SYNTAX_ADD(SSID_TYPE "none:")
	SYNTAX_ADD(SSID_TYPE "normal:")
	SYNTAX_ADD(SSID_TYPE ":not():")
	SYNTAX_ADD(SSID_TYPE ":nth-child():")
	SYNTAX_ADD(SSID_TYPE ":nth-column():")
	SYNTAX_ADD(SSID_TYPE ":nth-last-child():")
	SYNTAX_ADD(SSID_TYPE ":nth-last-column():")
	SYNTAX_ADD(SSID_TYPE ":nth-last-match():")
	SYNTAX_ADD(SSID_TYPE ":nth-last-of-type():")
	SYNTAX_ADD(SSID_TYPE ":nth-match():")
	SYNTAX_ADD(SSID_TYPE ":nth-of-type():")
	SYNTAX_ADD(SSID_TYPE "<number>:")
	SYNTAX_ADD(SSID_TYPE "-o-:")
	SYNTAX_ADD(SSID_TYPE "object-fit:")
	SYNTAX_ADD(SSID_TYPE "object-position:")
	SYNTAX_ADD(SSID_TYPE "oeb-column-number:")
	SYNTAX_ADD(SSID_TYPE "oeb-page-foot:")
	SYNTAX_ADD(SSID_TYPE "oeb-page-head:")
	SYNTAX_ADD(SSID_TYPE ":only-child:")
	SYNTAX_ADD(SSID_TYPE ":only-of-type:")
	SYNTAX_ADD(SSID_TYPE "opacity:")
	SYNTAX_ADD(SSID_TYPE ":optional:")
	SYNTAX_ADD(SSID_TYPE "order:")
	SYNTAX_ADD(SSID_TYPE "orient:")
	SYNTAX_ADD(SSID_TYPE "orientation:")
	SYNTAX_ADD(SSID_TYPE "orientation @?:")
	SYNTAX_ADD(SSID_TYPE "orphans:")
	SYNTAX_ADD(SSID_TYPE "outline:")
	SYNTAX_ADD(SSID_TYPE "outline-color:")
	SYNTAX_ADD(SSID_TYPE "outline-offset:")
	SYNTAX_ADD(SSID_TYPE "outline-radius:")
	SYNTAX_ADD(SSID_TYPE "outline-radius-bottomleft:")
	SYNTAX_ADD(SSID_TYPE "outline-radius-bottomright:")
	SYNTAX_ADD(SSID_TYPE "outline-radius-topleft:")
	SYNTAX_ADD(SSID_TYPE "outline-radius-topright:")
	SYNTAX_ADD(SSID_TYPE "outline-style:")
	SYNTAX_ADD(SSID_TYPE "outline-width:")
	SYNTAX_ADD(SSID_TYPE ":out-of-range:")
	SYNTAX_ADD(SSID_TYPE "::outside:")
	SYNTAX_ADD(SSID_TYPE "overflow:")
	SYNTAX_ADD(SSID_TYPE "overflow-scrolling:")
	SYNTAX_ADD(SSID_TYPE "overflow-style:")
	SYNTAX_ADD(SSID_TYPE "overflow-wrap:")
	SYNTAX_ADD(SSID_TYPE "overflow-x:")
	SYNTAX_ADD(SSID_TYPE "overflow-y:")
	SYNTAX_ADD(SSID_TYPE "padding:")
	SYNTAX_ADD(SSID_TYPE "padding-after:")
	SYNTAX_ADD(SSID_TYPE "padding-before:")
	SYNTAX_ADD(SSID_TYPE "padding-bottom:")
	SYNTAX_ADD(SSID_TYPE "padding-end:")
	SYNTAX_ADD(SSID_TYPE "padding-left:")
	SYNTAX_ADD(SSID_TYPE "padding-right:")
	SYNTAX_ADD(SSID_TYPE "padding-start:")
	SYNTAX_ADD(SSID_TYPE "padding-top:")
	SYNTAX_ADD(SSID_TYPE "page:")
	SYNTAX_ADD(SSID_TYPE "::page:")
	SYNTAX_ADD(SSID_TYPE "::page():")
	SYNTAX_ADD(SSID_TYPE "@page:")
	SYNTAX_ADD(SSID_TYPE "::pagebreak:")
	SYNTAX_ADD(SSID_TYPE "page-break-after:")
	SYNTAX_ADD(SSID_TYPE "page-break-before:")
	SYNTAX_ADD(SSID_TYPE "page-break-inside:")
	SYNTAX_ADD(SSID_TYPE "::page-column():")
	SYNTAX_ADD(SSID_TYPE "::pagecontent:")
	SYNTAX_ADD(SSID_TYPE "page-policy:")
	SYNTAX_ADD(SSID_TYPE "::page-sequence:")
	SYNTAX_ADD(SSID_TYPE "panose-1:")
	SYNTAX_ADD(SSID_TYPE ":past:")
	SYNTAX_ADD(SSID_TYPE "pause:")
	SYNTAX_ADD(SSID_TYPE "pause-after:")
	SYNTAX_ADD(SSID_TYPE "pause-before:")
	SYNTAX_ADD(SSID_TYPE "pc:")
	SYNTAX_ADD(SSID_TYPE "pending():")
	SYNTAX_ADD(SSID_TYPE "<percentage>:")
	SYNTAX_ADD(SSID_TYPE "perspective:")
	SYNTAX_ADD(SSID_TYPE "perspective():")
	SYNTAX_ADD(SSID_TYPE "perspective-origin:")
	SYNTAX_ADD(SSID_TYPE "perspective-origin-x:")
	SYNTAX_ADD(SSID_TYPE "perspective-origin-y:")
	SYNTAX_ADD(SSID_TYPE "phonemes:")
	SYNTAX_ADD(SSID_TYPE "pitch:")
	SYNTAX_ADD(SSID_TYPE "pitch-range:")
	SYNTAX_ADD(SSID_TYPE ":placeholder:")
	SYNTAX_ADD(SSID_TYPE "play-during:")
	SYNTAX_ADD(SSID_TYPE "pointer-events:")
	SYNTAX_ADD(SSID_TYPE "position:")
	SYNTAX_ADD(SSID_TYPE "<position>:")
	SYNTAX_ADD(SSID_TYPE "prefix:")
	SYNTAX_ADD(SSID_TYPE "presentation-level:")
	SYNTAX_ADD(SSID_TYPE "-prince-:")
	SYNTAX_ADD(SSID_TYPE "print-color-adjust:")
	SYNTAX_ADD(SSID_TYPE "progress-appearance:")
	SYNTAX_ADD(SSID_TYPE "pt:")
	SYNTAX_ADD(SSID_TYPE "punctuation-trim:")
	SYNTAX_ADD(SSID_TYPE "punctuation-wrap:")
	SYNTAX_ADD(SSID_TYPE "px:")
	SYNTAX_ADD(SSID_TYPE "quotes:")
	SYNTAX_ADD(SSID_TYPE "rad:")
	SYNTAX_ADD(SSID_TYPE "radial-gradient:")
	SYNTAX_ADD(SSID_TYPE "range:")
	SYNTAX_ADD(SSID_TYPE "<ratio>:")
	SYNTAX_ADD(SSID_TYPE ":read-only:")
	SYNTAX_ADD(SSID_TYPE ":read-write:")
	SYNTAX_ADD(SSID_TYPE "rect():")
	SYNTAX_ADD(SSID_TYPE "@region:")
	SYNTAX_ADD(SSID_TYPE "region-break-after:")
	SYNTAX_ADD(SSID_TYPE "region-break-before:")
	SYNTAX_ADD(SSID_TYPE "region-break-inside:")
	SYNTAX_ADD(SSID_TYPE "region-overflow:")
	SYNTAX_ADD(SSID_TYPE "rem:")
	SYNTAX_ADD(SSID_TYPE "rendering-intent:")
	SYNTAX_ADD(SSID_TYPE "::repeat-index:")
	SYNTAX_ADD(SSID_TYPE "repeating-linear-gradient():")
	SYNTAX_ADD(SSID_TYPE "repeating-radial-gradient():")
	SYNTAX_ADD(SSID_TYPE "::repeat-item:")
	SYNTAX_ADD(SSID_TYPE "replace:")
	SYNTAX_ADD(SSID_TYPE ":required:")
	SYNTAX_ADD(SSID_TYPE "resize:")
	SYNTAX_ADD(SSID_TYPE "resolution:")
	SYNTAX_ADD(SSID_TYPE "resolution @?:")
	SYNTAX_ADD(SSID_TYPE "<resolution>:")
	SYNTAX_ADD(SSID_TYPE "rest:")
	SYNTAX_ADD(SSID_TYPE "rest-after:")
	SYNTAX_ADD(SSID_TYPE "rest-before:")
	SYNTAX_ADD(SSID_TYPE "::reveal:")
	SYNTAX_ADD(SSID_TYPE "rgb():")
	SYNTAX_ADD(SSID_TYPE "rgba():")
	SYNTAX_ADD(SSID_TYPE "richness:")
	SYNTAX_ADD(SSID_TYPE "right:")
	SYNTAX_ADD(SSID_TYPE ":right:")
	SYNTAX_ADD(SSID_TYPE "-rim-:")
	SYNTAX_ADD(SSID_TYPE "-ro-:")
	SYNTAX_ADD(SSID_TYPE ":root:")
	SYNTAX_ADD(SSID_TYPE "rotate():")
	SYNTAX_ADD(SSID_TYPE "rotateX():")
	SYNTAX_ADD(SSID_TYPE "rotateY():")
	SYNTAX_ADD(SSID_TYPE "rotate3D():")
	SYNTAX_ADD(SSID_TYPE "rotateZ():")
	SYNTAX_ADD(SSID_TYPE "rotate3d():")
	SYNTAX_ADD(SSID_TYPE "rotation:")
	SYNTAX_ADD(SSID_TYPE "rotation-point:")
	SYNTAX_ADD(SSID_TYPE "row-span:")
	SYNTAX_ADD(SSID_TYPE "rounddown():")
	SYNTAX_ADD(SSID_TYPE "roundup():")
	SYNTAX_ADD(SSID_TYPE "rtl-ordering:")
	SYNTAX_ADD(SSID_TYPE "ruby-align:")
	SYNTAX_ADD(SSID_TYPE "ruby-overhang:")
	SYNTAX_ADD(SSID_TYPE "ruby-position:")
	SYNTAX_ADD(SSID_TYPE "ruby-span:")
	SYNTAX_ADD(SSID_TYPE "running():")
	SYNTAX_ADD(SSID_TYPE "scale():")
	SYNTAX_ADD(SSID_TYPE "scaleX():")
	SYNTAX_ADD(SSID_TYPE "scaleY():")
	SYNTAX_ADD(SSID_TYPE "scaleZ():")
	SYNTAX_ADD(SSID_TYPE "scale3d(X):")
	SYNTAX_ADD(SSID_TYPE "scan @?:")
	SYNTAX_ADD(SSID_TYPE "::selection:")
	SYNTAX_ADD(SSID_TYPE "separator-image:")
	SYNTAX_ADD(SSID_TYPE "set-link-source:")
	SYNTAX_ADD(SSID_TYPE "<shape>:")
	SYNTAX_ADD(SSID_TYPE "shape-inside:")
	SYNTAX_ADD(SSID_TYPE "shape-margin:")
	SYNTAX_ADD(SSID_TYPE "shape-outside:")
	SYNTAX_ADD(SSID_TYPE "shape-padding:")
	SYNTAX_ADD(SSID_TYPE ":scope:")
	SYNTAX_ADD(SSID_TYPE "script-level:")
	SYNTAX_ADD(SSID_TYPE "script-min-size:")
	SYNTAX_ADD(SSID_TYPE "script-size-multiplier:")
	SYNTAX_ADD(SSID_TYPE "scrollbar-3dlight-color property:")
	SYNTAX_ADD(SSID_TYPE "scrollbar-arrow-color:")
	SYNTAX_ADD(SSID_TYPE "scrollbar-base-color:")
	SYNTAX_ADD(SSID_TYPE "scrollbar-darkshadow-color:")
	SYNTAX_ADD(SSID_TYPE "scrollbar-end-backward @?:")
	SYNTAX_ADD(SSID_TYPE "scrollbar-end-forward @?:")
	SYNTAX_ADD(SSID_TYPE "scrollbar-face-color:")
	SYNTAX_ADD(SSID_TYPE "scrollbar-highlight-color:")
	SYNTAX_ADD(SSID_TYPE "scrollbar-shadow-color:")
	SYNTAX_ADD(SSID_TYPE "scrollbar-start-backward @?:")
	SYNTAX_ADD(SSID_TYPE "scrollbar-start-forward @?:")
	SYNTAX_ADD(SSID_TYPE "scrollbar-thumb-proportional @?:")
	SYNTAX_ADD(SSID_TYPE "scrollbar-track-color:")
	SYNTAX_ADD(SSID_TYPE "scroll-chaining:")
	SYNTAX_ADD(SSID_TYPE "scroll-limit:")
	SYNTAX_ADD(SSID_TYPE "scroll-limit-x-max:")
	SYNTAX_ADD(SSID_TYPE "scroll-limit-x-min:")
	SYNTAX_ADD(SSID_TYPE "scroll-limit-y-max:")
	SYNTAX_ADD(SSID_TYPE "scroll-limit-y-min:")
	SYNTAX_ADD(SSID_TYPE "scroll-rails:")
	SYNTAX_ADD(SSID_TYPE "scroll-snap-points-x:")
	SYNTAX_ADD(SSID_TYPE "scroll-snap-points-y:")
	SYNTAX_ADD(SSID_TYPE "scroll-snap-type:")
	SYNTAX_ADD(SSID_TYPE "scroll-snap-x:")
	SYNTAX_ADD(SSID_TYPE "scroll-snap-y:")
	SYNTAX_ADD(SSID_TYPE "scroll-translation:")
	SYNTAX_ADD(SSID_TYPE "::scrolled-canvas:")
	SYNTAX_ADD(SSID_TYPE "::scrolled-content:")
	SYNTAX_ADD(SSID_TYPE "::scrolled-page-sequence:")
	SYNTAX_ADD(SSID_TYPE "::selection:")
	SYNTAX_ADD(SSID_TYPE "shape-image-threshold:")
	SYNTAX_ADD(SSID_TYPE "shape-inside:")
	SYNTAX_ADD(SSID_TYPE "shape-margin:")
	SYNTAX_ADD(SSID_TYPE "shape-outside:")
	SYNTAX_ADD(SSID_TYPE "shape-padding:")
	SYNTAX_ADD(SSID_TYPE "shape-rendering:")
	SYNTAX_ADD(SSID_TYPE "size:")
	SYNTAX_ADD(SSID_TYPE "skew():")
	SYNTAX_ADD(SSID_TYPE "skewX():")
	SYNTAX_ADD(SSID_TYPE "skewY():")
	SYNTAX_ADD(SSID_TYPE "skewZ():")
	SYNTAX_ADD(SSID_TYPE "skew3D(X):")
	SYNTAX_ADD(SSID_TYPE "::slot():")
	SYNTAX_ADD(SSID_TYPE "speak:")
	SYNTAX_ADD(SSID_TYPE "speak-as:")
	SYNTAX_ADD(SSID_TYPE "speak-header:")
	SYNTAX_ADD(SSID_TYPE "speak-numeral:")
	SYNTAX_ADD(SSID_TYPE "speak-punctuation:")
	SYNTAX_ADD(SSID_TYPE "speech-rate:")
	SYNTAX_ADD(SSID_TYPE "src:")
	SYNTAX_ADD(SSID_TYPE "stack-sizing:")
	SYNTAX_ADD(SSID_TYPE "steps():")
	SYNTAX_ADD(SSID_TYPE "stop-color:")
	SYNTAX_ADD(SSID_TYPE "stop-opacity:")
	SYNTAX_ADD(SSID_TYPE "stress:")
	SYNTAX_ADD(SSID_TYPE "@string:")
	SYNTAX_ADD(SSID_TYPE "string():")
	SYNTAX_ADD(SSID_TYPE "<string>:")
	SYNTAX_ADD(SSID_TYPE "string-set:")
	SYNTAX_ADD(SSID_TYPE "stroke:")
	SYNTAX_ADD(SSID_TYPE "stroke-dasharray:")
	SYNTAX_ADD(SSID_TYPE "stroke-dashoffset:")
	SYNTAX_ADD(SSID_TYPE "stroke-linecap:")
	SYNTAX_ADD(SSID_TYPE "stroke-linejoin:")
	SYNTAX_ADD(SSID_TYPE "stroke-miterlimit:")
	SYNTAX_ADD(SSID_TYPE "stroke-opacity:")
	SYNTAX_ADD(SSID_TYPE "stroke-width:")
	SYNTAX_ADD(SSID_TYPE ":submit-invalid:")
	SYNTAX_ADD(SSID_TYPE "suffix:")
	SYNTAX_ADD(SSID_TYPE "@supports:")
	SYNTAX_ADD(SSID_TYPE ":suppressed:")
	SYNTAX_ADD(SSID_TYPE "::svg-foreign-content:")
	SYNTAX_ADD(SSID_TYPE "svg-shadow:")
	SYNTAX_ADD(SSID_TYPE "symbols:")
	SYNTAX_ADD(SSID_TYPE "symbols():")
	SYNTAX_ADD(SSID_TYPE "system:")
	SYNTAX_ADD(SSID_TYPE ":system-metric():")
	SYNTAX_ADD(SSID_TYPE "::table:")
	SYNTAX_ADD(SSID_TYPE "table-baseline:")
	SYNTAX_ADD(SSID_TYPE "table-border-color-dark:")
	SYNTAX_ADD(SSID_TYPE "table-border-color-light:")
	SYNTAX_ADD(SSID_TYPE "::table-cell:")
	SYNTAX_ADD(SSID_TYPE "::table-column:")
	SYNTAX_ADD(SSID_TYPE "::table-column-group:")
	SYNTAX_ADD(SSID_TYPE "::table-cell:")
	SYNTAX_ADD(SSID_TYPE "table-layout:")
	SYNTAX_ADD(SSID_TYPE "::table-outer:")
	SYNTAX_ADD(SSID_TYPE "::table-row:")
	SYNTAX_ADD(SSID_TYPE "::table-row-group:")
	SYNTAX_ADD(SSID_TYPE "tab-size:")
	SYNTAX_ADD(SSID_TYPE "tab-stops:")
	SYNTAX_ADD(SSID_TYPE "tap-highlight-color:")
	SYNTAX_ADD(SSID_TYPE "target:")
	SYNTAX_ADD(SSID_TYPE ":target:")
	SYNTAX_ADD(SSID_TYPE "target-counter():")
	SYNTAX_ADD(SSID_TYPE "target-counters():")
	SYNTAX_ADD(SSID_TYPE "target-name:")
	SYNTAX_ADD(SSID_TYPE "target-new:")
	SYNTAX_ADD(SSID_TYPE "target-position:")
	SYNTAX_ADD(SSID_TYPE "target-pull():")
	SYNTAX_ADD(SSID_TYPE "target-text():")
	SYNTAX_ADD(SSID_TYPE "-tc-:")
	SYNTAX_ADD(SSID_TYPE "text-anchor:")
	SYNTAX_ADD(SSID_TYPE "text-align:")
	SYNTAX_ADD(SSID_TYPE "text-align-last:")
	SYNTAX_ADD(SSID_TYPE "text-autospace:")
	SYNTAX_ADD(SSID_TYPE "text-blink:")
	SYNTAX_ADD(SSID_TYPE "text-combine:")
	SYNTAX_ADD(SSID_TYPE "text-combine-horizontal:")
	SYNTAX_ADD(SSID_TYPE "text-decoration:")
	SYNTAX_ADD(SSID_TYPE "text-decoration-color:")
	SYNTAX_ADD(SSID_TYPE "text-decoration-line:")
	SYNTAX_ADD(SSID_TYPE "text-decorations-in-effect:")
	SYNTAX_ADD(SSID_TYPE "text-decoration-skip:")
	SYNTAX_ADD(SSID_TYPE "text-decoration-style:")
	SYNTAX_ADD(SSID_TYPE "text-effect:")
	SYNTAX_ADD(SSID_TYPE "text-emphasis:")
	SYNTAX_ADD(SSID_TYPE "text-emphasis-color:")
	SYNTAX_ADD(SSID_TYPE "text-emphasis-position:")
	SYNTAX_ADD(SSID_TYPE "text-emphasis-skip:")
	SYNTAX_ADD(SSID_TYPE "text-emphasis-style:")
	SYNTAX_ADD(SSID_TYPE "text-fill-color:")
	SYNTAX_ADD(SSID_TYPE "text-fit:")
	SYNTAX_ADD(SSID_TYPE "text-height:")
	SYNTAX_ADD(SSID_TYPE "text-indent:")
	SYNTAX_ADD(SSID_TYPE "text-justify:")
	SYNTAX_ADD(SSID_TYPE "text-justify-trim:")
	SYNTAX_ADD(SSID_TYPE "text-kashida:")
	SYNTAX_ADD(SSID_TYPE "text-kashida-space:")
	SYNTAX_ADD(SSID_TYPE "text-line-through:")
	SYNTAX_ADD(SSID_TYPE "text-orientation:")
	SYNTAX_ADD(SSID_TYPE "text-outline:")
	SYNTAX_ADD(SSID_TYPE "text-overflow:")
	SYNTAX_ADD(SSID_TYPE "text-rendering:")
	SYNTAX_ADD(SSID_TYPE "text-security:")
	SYNTAX_ADD(SSID_TYPE "text-shadow:")
	SYNTAX_ADD(SSID_TYPE "text-size-adjust:")
	SYNTAX_ADD(SSID_TYPE "text-space-collapse:")
	SYNTAX_ADD(SSID_TYPE "text-spacing:")
	SYNTAX_ADD(SSID_TYPE "text-stroke:")
	SYNTAX_ADD(SSID_TYPE "text-stroke-color:")
	SYNTAX_ADD(SSID_TYPE "text-stroke-width:")
	SYNTAX_ADD(SSID_TYPE "text-transform:")
	SYNTAX_ADD(SSID_TYPE "text-trim:")
	SYNTAX_ADD(SSID_TYPE "text-underline:")
	SYNTAX_ADD(SSID_TYPE "text-underline-color:")
	SYNTAX_ADD(SSID_TYPE "text-underline-position:")
	SYNTAX_ADD(SSID_TYPE "text-underline-style:")
	SYNTAX_ADD(SSID_TYPE "text-wrap:")
	SYNTAX_ADD(SSID_TYPE "::thumb:")
	SYNTAX_ADD(SSID_TYPE "::ticks-after:")
	SYNTAX_ADD(SSID_TYPE "::ticks-before:")
	SYNTAX_ADD(SSID_TYPE "<timing-function>:")
	SYNTAX_ADD(SSID_TYPE "toggle():")
	SYNTAX_ADD(SSID_TYPE "::tooltip:")
	SYNTAX_ADD(SSID_TYPE "top:")
	SYNTAX_ADD(SSID_TYPE "top-bar-button:")
	SYNTAX_ADD(SSID_TYPE "touch-action:")
	SYNTAX_ADD(SSID_TYPE "touch-callout:")
	SYNTAX_ADD(SSID_TYPE "touch-enabled @?:")
	SYNTAX_ADD(SSID_TYPE "::track:")
	SYNTAX_ADD(SSID_TYPE "transform:")
	SYNTAX_ADD(SSID_TYPE "transform-origin:")
	SYNTAX_ADD(SSID_TYPE "transform-origin-x:")
	SYNTAX_ADD(SSID_TYPE "transform-origin-y:")
	SYNTAX_ADD(SSID_TYPE "transform-origin-z:")
	SYNTAX_ADD(SSID_TYPE "transform-style:")
	SYNTAX_ADD(SSID_TYPE "transition:")
	SYNTAX_ADD(SSID_TYPE "transition-delay:")
	SYNTAX_ADD(SSID_TYPE "transition-duration:")
	SYNTAX_ADD(SSID_TYPE "transition-property:")
	SYNTAX_ADD(SSID_TYPE "transition-repeat-count:")
	SYNTAX_ADD(SSID_TYPE "transition-timing-function:")
	SYNTAX_ADD(SSID_TYPE "translate():")
	SYNTAX_ADD(SSID_TYPE "translateX():")
	SYNTAX_ADD(SSID_TYPE "translateY():")
	SYNTAX_ADD(SSID_TYPE "translateZ():")
	SYNTAX_ADD(SSID_TYPE "translate3d():")
	SYNTAX_ADD(SSID_TYPE ":tree-checkbox:")
	SYNTAX_ADD(SSID_TYPE ":tree-cell:")
	SYNTAX_ADD(SSID_TYPE ":tree-cell-text:")
	SYNTAX_ADD(SSID_TYPE ":tree-cell-text(hover):")
	SYNTAX_ADD(SSID_TYPE ":tree-column:")
	SYNTAX_ADD(SSID_TYPE ":tree-drop-feedback:")
	SYNTAX_ADD(SSID_TYPE ":tree-image:")
	SYNTAX_ADD(SSID_TYPE ":tree-indentation:")
	SYNTAX_ADD(SSID_TYPE ":tree-line:")
	SYNTAX_ADD(SSID_TYPE ":tree-progressmeter:")
	SYNTAX_ADD(SSID_TYPE ":tree-row:")
	SYNTAX_ADD(SSID_TYPE ":tree-row(hover):")
	SYNTAX_ADD(SSID_TYPE ":tree-separator:")
	SYNTAX_ADD(SSID_TYPE ":tree-twisty:")
	SYNTAX_ADD(SSID_TYPE "turn:")
	SYNTAX_ADD(SSID_TYPE ":ui-invalid:")
	SYNTAX_ADD(SSID_TYPE ":ui-valid:")
	SYNTAX_ADD(SSID_TYPE "unicode-bidi:")
	SYNTAX_ADD(SSID_TYPE "unicode-range:")
	SYNTAX_ADD(SSID_TYPE "<uri>:")
	SYNTAX_ADD(SSID_TYPE "url():")
	SYNTAX_ADD(SSID_TYPE "use-link-source:")
	SYNTAX_ADD(SSID_TYPE "user-drag:")
	SYNTAX_ADD(SSID_TYPE ":user-error:")
	SYNTAX_ADD(SSID_TYPE "user-focus:")
	SYNTAX_ADD(SSID_TYPE "<user-ident>:")
	SYNTAX_ADD(SSID_TYPE "user-input:")
	SYNTAX_ADD(SSID_TYPE "user-modify:")
	SYNTAX_ADD(SSID_TYPE "user-select:")
	SYNTAX_ADD(SSID_TYPE "user-zoom:")
	SYNTAX_ADD(SSID_TYPE ":valid:")
	SYNTAX_ADD(SSID_TYPE "::value:")
	SYNTAX_ADD(SSID_TYPE "var():")
	SYNTAX_ADD(SSID_TYPE "var-*:")
	SYNTAX_ADD(SSID_TYPE "vector-effect:")
	SYNTAX_ADD(SSID_TYPE "vertical-align:")
	SYNTAX_ADD(SSID_TYPE "version:")
	SYNTAX_ADD(SSID_TYPE "vh:")
	SYNTAX_ADD(SSID_TYPE "@viewport:")
	SYNTAX_ADD(SSID_TYPE ":viewport:")
	SYNTAX_ADD(SSID_TYPE "@viewport:")
	SYNTAX_ADD(SSID_TYPE ":viewport-scroll:")
	SYNTAX_ADD(SSID_TYPE "visibility:")
	SYNTAX_ADD(SSID_TYPE ":visited:")
	SYNTAX_ADD(SSID_TYPE "vmax:")
	SYNTAX_ADD(SSID_TYPE "vmin:")
	SYNTAX_ADD(SSID_TYPE "voice-balance:")
	SYNTAX_ADD(SSID_TYPE "voice-duration:")
	SYNTAX_ADD(SSID_TYPE "voice-family:")
	SYNTAX_ADD(SSID_TYPE "voice-pitch:")
	SYNTAX_ADD(SSID_TYPE "voice-pitch-range:")
	SYNTAX_ADD(SSID_TYPE "voice-range:")
	SYNTAX_ADD(SSID_TYPE "voice-rate:")
	SYNTAX_ADD(SSID_TYPE "voice-stress:")
	SYNTAX_ADD(SSID_TYPE "voice-volume:")
	SYNTAX_ADD(SSID_TYPE "volume:")
	SYNTAX_ADD(SSID_TYPE "vw:")
	SYNTAX_ADD(SSID_TYPE "-wap-:")
	SYNTAX_ADD(SSID_TYPE "-webkit-:")
	SYNTAX_ADD(SSID_TYPE "white-space:")
	SYNTAX_ADD(SSID_TYPE "widows:")
	SYNTAX_ADD(SSID_TYPE "width:")
	SYNTAX_ADD(SSID_TYPE "width @?:")
	SYNTAX_ADD(SSID_TYPE ":window-inactive:")
	SYNTAX_ADD(SSID_TYPE "windows-classic @?:")
	SYNTAX_ADD(SSID_TYPE "windows-compositor @?:")
	SYNTAX_ADD(SSID_TYPE "windows-default-theme @?:")
	SYNTAX_ADD(SSID_TYPE "window-shadow:")
	SYNTAX_ADD(SSID_TYPE "windows-theme @?:")
	SYNTAX_ADD(SSID_TYPE "word-break:")
	SYNTAX_ADD(SSID_TYPE "word-spacing:")
	SYNTAX_ADD(SSID_TYPE "word-wrap:")
	SYNTAX_ADD(SSID_TYPE "wrap:")
	SYNTAX_ADD(SSID_TYPE "wrap-flow:")
	SYNTAX_ADD(SSID_TYPE "wrap-margin:")
	SYNTAX_ADD(SSID_TYPE "wrap-padding:")
	SYNTAX_ADD(SSID_TYPE "wrap-through:")
	SYNTAX_ADD(SSID_TYPE "writing-mode:")
	SYNTAX_ADD(SSID_TYPE "::xul-anonymous-block:")
	SYNTAX_ADD(SSID_TYPE "-xv-:")
	SYNTAX_ADD(SSID_TYPE "z-index:")
	SYNTAX_ADD(SSID_TYPE "zoom:")
	SYNTAX_ADD(SSID_NUMBER "%")
	SYNTAX_ADD(SSID_NUMBER "px")
	SYNTAX_ADD(SSID_NUMBER "vw")
	SYNTAX_ADD(SSID_NUMBER "vh")
	SYNTAX_ADD(SSID_NUMBER "em")
	SYNTAX_ADD(SSID_NUMBER "ep")
	SYNTAX_ADD_RANGE(SSID_COMMENT "/*", "*/")
	SYNTAX_ADD_RANGE(SSID_MACRO ".", " ")
	SYNTAX_ADD_RANGE(SSID_MACRO "#", " ")
	SYNTAX_ADD_RANGE(SSID_STRING "\"", "\"")
	SYNTAX_ADD_RANGE(SSID_STRING "'", "'")
SYNTAX_END(syntax_css)

SYNTAX_NEW(syntax_html)
	SYNTAX_EXT_COUNT(1)
	SYNTAX_ADD_EXT(".html")
	SYNTAX_ADD(SSID_KEYWORD "–")
	SYNTAX_ADD(SSID_KEYWORD "DOCTYPE")
	SYNTAX_ADD(SSID_KEYWORD "a")
	SYNTAX_ADD(SSID_KEYWORD "abbr")
	SYNTAX_ADD(SSID_KEYWORD "acronym")
	SYNTAX_ADD(SSID_KEYWORD "address")
	SYNTAX_ADD(SSID_KEYWORD "applet")
	SYNTAX_ADD(SSID_KEYWORD "area")
	SYNTAX_ADD(SSID_KEYWORD "article")
	SYNTAX_ADD(SSID_KEYWORD "aside")
	SYNTAX_ADD(SSID_KEYWORD "audio")
	SYNTAX_ADD(SSID_KEYWORD "b")
	SYNTAX_ADD(SSID_KEYWORD "base")
	SYNTAX_ADD(SSID_KEYWORD "basefont")
	SYNTAX_ADD(SSID_KEYWORD "bdo")
	SYNTAX_ADD(SSID_KEYWORD "big")
	SYNTAX_ADD(SSID_KEYWORD "blockquote")
	SYNTAX_ADD(SSID_KEYWORD "body")
	SYNTAX_ADD(SSID_KEYWORD "br")
	SYNTAX_ADD(SSID_KEYWORD "button")
	SYNTAX_ADD(SSID_KEYWORD "canvas")
	SYNTAX_ADD(SSID_KEYWORD "caption")
	SYNTAX_ADD(SSID_KEYWORD "center")
	SYNTAX_ADD(SSID_KEYWORD "cite")
	SYNTAX_ADD(SSID_KEYWORD "code")
	SYNTAX_ADD(SSID_KEYWORD "col")
	SYNTAX_ADD(SSID_KEYWORD "colgroup")
	SYNTAX_ADD(SSID_KEYWORD "datalist")
	SYNTAX_ADD(SSID_KEYWORD "dd")
	SYNTAX_ADD(SSID_KEYWORD "del")
	SYNTAX_ADD(SSID_KEYWORD "dfn")
	SYNTAX_ADD(SSID_KEYWORD "div")
	SYNTAX_ADD(SSID_KEYWORD "dl")
	SYNTAX_ADD(SSID_KEYWORD "dt")
	SYNTAX_ADD(SSID_KEYWORD "em")
	SYNTAX_ADD(SSID_KEYWORD "embed")
	SYNTAX_ADD(SSID_KEYWORD "fieldset")
	SYNTAX_ADD(SSID_KEYWORD "figcaption")
	SYNTAX_ADD(SSID_KEYWORD "figure")
	SYNTAX_ADD(SSID_KEYWORD "font")
	SYNTAX_ADD(SSID_KEYWORD "footer")
	SYNTAX_ADD(SSID_KEYWORD "form")
	SYNTAX_ADD(SSID_KEYWORD "frame")
	SYNTAX_ADD(SSID_KEYWORD "frameset")
	SYNTAX_ADD(SSID_KEYWORD "head")
	SYNTAX_ADD(SSID_KEYWORD "header")
	SYNTAX_ADD(SSID_KEYWORD "h1")
	SYNTAX_ADD(SSID_KEYWORD "h2")
	SYNTAX_ADD(SSID_KEYWORD "h3")
	SYNTAX_ADD(SSID_KEYWORD "h4")
	SYNTAX_ADD(SSID_KEYWORD "h5")
	SYNTAX_ADD(SSID_KEYWORD "h6")
	SYNTAX_ADD(SSID_KEYWORD "hr")
	SYNTAX_ADD(SSID_KEYWORD "html")
	SYNTAX_ADD(SSID_KEYWORD "!DOCTYPE")
	SYNTAX_ADD(SSID_KEYWORD "i")
	SYNTAX_ADD(SSID_KEYWORD "iframe")
	SYNTAX_ADD(SSID_KEYWORD "img")
	SYNTAX_ADD(SSID_KEYWORD "input")
	SYNTAX_ADD(SSID_KEYWORD "ins")
	SYNTAX_ADD(SSID_KEYWORD "kbd")
	SYNTAX_ADD(SSID_KEYWORD "label")
	SYNTAX_ADD(SSID_KEYWORD "legend")
	SYNTAX_ADD(SSID_KEYWORD "li")
	SYNTAX_ADD(SSID_KEYWORD "link")
	SYNTAX_ADD(SSID_KEYWORD "main")
	SYNTAX_ADD(SSID_KEYWORD "map")
	SYNTAX_ADD(SSID_KEYWORD "mark")
	SYNTAX_ADD(SSID_KEYWORD "meta")
	SYNTAX_ADD(SSID_KEYWORD "meter")
	SYNTAX_ADD(SSID_KEYWORD "nav")
	SYNTAX_ADD(SSID_KEYWORD "noscript")
	SYNTAX_ADD(SSID_KEYWORD "object")
	SYNTAX_ADD(SSID_KEYWORD "ol")
	SYNTAX_ADD(SSID_KEYWORD "optgroup")
	SYNTAX_ADD(SSID_KEYWORD "option")
	SYNTAX_ADD(SSID_KEYWORD "p")
	SYNTAX_ADD(SSID_KEYWORD "param")
	SYNTAX_ADD(SSID_KEYWORD "pre")
	SYNTAX_ADD(SSID_KEYWORD "progress")
	SYNTAX_ADD(SSID_KEYWORD "q")
	SYNTAX_ADD(SSID_KEYWORD "s")
	SYNTAX_ADD(SSID_KEYWORD "samp")
	SYNTAX_ADD(SSID_KEYWORD "script")
	SYNTAX_ADD(SSID_KEYWORD "section")
	SYNTAX_ADD(SSID_KEYWORD "select")
	SYNTAX_ADD(SSID_KEYWORD "small")
	SYNTAX_ADD(SSID_KEYWORD "source")
	SYNTAX_ADD(SSID_KEYWORD "span")
	SYNTAX_ADD(SSID_KEYWORD "strike")
	SYNTAX_ADD(SSID_KEYWORD "strong")
	SYNTAX_ADD(SSID_KEYWORD "style")
	SYNTAX_ADD(SSID_KEYWORD "sub")
	SYNTAX_ADD(SSID_KEYWORD "sup")
	SYNTAX_ADD(SSID_KEYWORD "table")
	SYNTAX_ADD(SSID_KEYWORD "tbody")
	SYNTAX_ADD(SSID_KEYWORD "td")
	SYNTAX_ADD(SSID_KEYWORD "textarea")
	SYNTAX_ADD(SSID_KEYWORD "tfoot")
	SYNTAX_ADD(SSID_KEYWORD "th")
	SYNTAX_ADD(SSID_KEYWORD "thead")
	SYNTAX_ADD(SSID_KEYWORD "time")
	SYNTAX_ADD(SSID_KEYWORD "title")
	SYNTAX_ADD(SSID_KEYWORD "tr")
	SYNTAX_ADD(SSID_KEYWORD "u")
	SYNTAX_ADD(SSID_KEYWORD "ul")
	SYNTAX_ADD(SSID_KEYWORD "var")
	SYNTAX_ADD(SSID_KEYWORD "video")
	SYNTAX_ADD(SSID_KEYWORD "wbr")
	SYNTAX_ADD(SSID_TYPE "accept")
	SYNTAX_ADD(SSID_TYPE "accept-charset")
	SYNTAX_ADD(SSID_TYPE "accesskey")
	SYNTAX_ADD(SSID_TYPE "action")
	SYNTAX_ADD(SSID_TYPE "align")
	SYNTAX_ADD(SSID_TYPE "alt")
	SYNTAX_ADD(SSID_TYPE "async")
	SYNTAX_ADD(SSID_TYPE "attributeName")
	SYNTAX_ADD(SSID_TYPE "autocomplete")
	SYNTAX_ADD(SSID_TYPE "autofocus")
	SYNTAX_ADD(SSID_TYPE "autoplay")
	SYNTAX_ADD(SSID_TYPE "begin")
	SYNTAX_ADD(SSID_TYPE "bgcolor")
	SYNTAX_ADD(SSID_TYPE "border")
	SYNTAX_ADD(SSID_TYPE "calcMode")
	SYNTAX_ADD(SSID_TYPE "charset")
	SYNTAX_ADD(SSID_TYPE "checked")
	SYNTAX_ADD(SSID_TYPE "cite")
	SYNTAX_ADD(SSID_TYPE "clip-rule")
	SYNTAX_ADD(SSID_TYPE "class")
	SYNTAX_ADD(SSID_TYPE "color")
	SYNTAX_ADD(SSID_TYPE "cols")
	SYNTAX_ADD(SSID_TYPE "colspan")
	SYNTAX_ADD(SSID_TYPE "content")
	SYNTAX_ADD(SSID_TYPE "contenteditable")
	SYNTAX_ADD(SSID_TYPE "controls")
	SYNTAX_ADD(SSID_TYPE "coords")
	SYNTAX_ADD(SSID_TYPE "crossorigin")
	SYNTAX_ADD(SSID_TYPE "d")
	SYNTAX_ADD(SSID_TYPE "data")
	SYNTAX_ADD(SSID_TYPE "datetime")
	SYNTAX_ADD(SSID_TYPE "default")
	SYNTAX_ADD(SSID_TYPE "defer")
	SYNTAX_ADD(SSID_TYPE "dir")
	SYNTAX_ADD(SSID_TYPE "direction")
	SYNTAX_ADD(SSID_TYPE "dirname")
	SYNTAX_ADD(SSID_TYPE "disabled")
	SYNTAX_ADD(SSID_TYPE "download")
	SYNTAX_ADD(SSID_TYPE "draggable")
	SYNTAX_ADD(SSID_TYPE "dur")
	SYNTAX_ADD(SSID_TYPE "enctype")
	SYNTAX_ADD(SSID_TYPE "fill")
	SYNTAX_ADD(SSID_TYPE "fill-rule")
	SYNTAX_ADD(SSID_TYPE "for")
	SYNTAX_ADD(SSID_TYPE "form")
	SYNTAX_ADD(SSID_TYPE "formaction")
	SYNTAX_ADD(SSID_TYPE "from")
	SYNTAX_ADD(SSID_TYPE "headers")
	SYNTAX_ADD(SSID_TYPE "height")
	SYNTAX_ADD(SSID_TYPE "hidden")
	SYNTAX_ADD(SSID_TYPE "high")
	SYNTAX_ADD(SSID_TYPE "href")
	SYNTAX_ADD(SSID_TYPE "hreflang")
	SYNTAX_ADD(SSID_TYPE "http-equiv")
	SYNTAX_ADD(SSID_TYPE "icon")
	SYNTAX_ADD(SSID_TYPE "id")
	SYNTAX_ADD(SSID_TYPE "ismap")
	SYNTAX_ADD(SSID_TYPE "integrity")
	SYNTAX_ADD(SSID_TYPE "kind")
	SYNTAX_ADD(SSID_TYPE "keySplines")
	SYNTAX_ADD(SSID_TYPE "keyTimes")
	SYNTAX_ADD(SSID_TYPE "lang")
	SYNTAX_ADD(SSID_TYPE "langlabel")
	SYNTAX_ADD(SSID_TYPE "list")
	SYNTAX_ADD(SSID_TYPE "loop")
	SYNTAX_ADD(SSID_TYPE "low")
	SYNTAX_ADD(SSID_TYPE "max")
	SYNTAX_ADD(SSID_TYPE "maxlength")
	SYNTAX_ADD(SSID_TYPE "media")
	SYNTAX_ADD(SSID_TYPE "method")
	SYNTAX_ADD(SSID_TYPE "min")
	SYNTAX_ADD(SSID_TYPE "multiple")
	SYNTAX_ADD(SSID_TYPE "muted")
	SYNTAX_ADD(SSID_TYPE "name")
	SYNTAX_ADD(SSID_TYPE "novalidate")
	SYNTAX_ADD(SSID_TYPE "onabort")
	SYNTAX_ADD(SSID_TYPE "onafterprint")
	SYNTAX_ADD(SSID_TYPE "onbeforeprint")
	SYNTAX_ADD(SSID_TYPE "onbeforeunload")
	SYNTAX_ADD(SSID_TYPE "onblur")
	SYNTAX_ADD(SSID_TYPE "oncanplay")
	SYNTAX_ADD(SSID_TYPE "oncanplaythrough")
	SYNTAX_ADD(SSID_TYPE "onchange")
	SYNTAX_ADD(SSID_TYPE "onclick")
	SYNTAX_ADD(SSID_TYPE "oncontextmenu")
	SYNTAX_ADD(SSID_TYPE "oncopy")
	SYNTAX_ADD(SSID_TYPE "oncuechange")
	SYNTAX_ADD(SSID_TYPE "oncut")
	SYNTAX_ADD(SSID_TYPE "ondblclick")
	SYNTAX_ADD(SSID_TYPE "ondrag")
	SYNTAX_ADD(SSID_TYPE "ondragend")
	SYNTAX_ADD(SSID_TYPE "ondragenter")
	SYNTAX_ADD(SSID_TYPE "ondragleave")
	SYNTAX_ADD(SSID_TYPE "ondragover")
	SYNTAX_ADD(SSID_TYPE "ondragstart")
	SYNTAX_ADD(SSID_TYPE "ondrop")
	SYNTAX_ADD(SSID_TYPE "ondurationchange")
	SYNTAX_ADD(SSID_TYPE "onemptied")
	SYNTAX_ADD(SSID_TYPE "onended")
	SYNTAX_ADD(SSID_TYPE "onerror")
	SYNTAX_ADD(SSID_TYPE "onfocus")
	SYNTAX_ADD(SSID_TYPE "onhaschange")
	SYNTAX_ADD(SSID_TYPE "oninput")
	SYNTAX_ADD(SSID_TYPE "oninvalid")
	SYNTAX_ADD(SSID_TYPE "onkeydown")
	SYNTAX_ADD(SSID_TYPE "onkeypress")
	SYNTAX_ADD(SSID_TYPE "onkeyup")
	SYNTAX_ADD(SSID_TYPE "onload")
	SYNTAX_ADD(SSID_TYPE "onloadeddata")
	SYNTAX_ADD(SSID_TYPE "onloadedmetadata")
	SYNTAX_ADD(SSID_TYPE "onloadstart")
	SYNTAX_ADD(SSID_TYPE "onmousedown")
	SYNTAX_ADD(SSID_TYPE "onmousemove")
	SYNTAX_ADD(SSID_TYPE "onmouseout")
	SYNTAX_ADD(SSID_TYPE "onmouseover")
	SYNTAX_ADD(SSID_TYPE "onmouseup")
	SYNTAX_ADD(SSID_TYPE "onmousewheel")
	SYNTAX_ADD(SSID_TYPE "onoffline")
	SYNTAX_ADD(SSID_TYPE "ononline")
	SYNTAX_ADD(SSID_TYPE "onpagehide")
	SYNTAX_ADD(SSID_TYPE "onpageshow")
	SYNTAX_ADD(SSID_TYPE "onpaste")
	SYNTAX_ADD(SSID_TYPE "onpause")
	SYNTAX_ADD(SSID_TYPE "onplay")
	SYNTAX_ADD(SSID_TYPE "onplaying")
	SYNTAX_ADD(SSID_TYPE "onpopstate")
	SYNTAX_ADD(SSID_TYPE "onprogress")
	SYNTAX_ADD(SSID_TYPE "onratechange")
	SYNTAX_ADD(SSID_TYPE "onreset")
	SYNTAX_ADD(SSID_TYPE "onresize")
	SYNTAX_ADD(SSID_TYPE "onscroll")
	SYNTAX_ADD(SSID_TYPE "onsearch")
	SYNTAX_ADD(SSID_TYPE "onseeked")
	SYNTAX_ADD(SSID_TYPE "onseeking")
	SYNTAX_ADD(SSID_TYPE "onselect")
	SYNTAX_ADD(SSID_TYPE "onstalled")
	SYNTAX_ADD(SSID_TYPE "onstorage")
	SYNTAX_ADD(SSID_TYPE "onsubmit")
	SYNTAX_ADD(SSID_TYPE "onsuspend")
	SYNTAX_ADD(SSID_TYPE "ontimeupdate")
	SYNTAX_ADD(SSID_TYPE "ontoggle")
	SYNTAX_ADD(SSID_TYPE "onunload")
	SYNTAX_ADD(SSID_TYPE "onvolumechange")
	SYNTAX_ADD(SSID_TYPE "onwaiting")
	SYNTAX_ADD(SSID_TYPE "onwheel")
	SYNTAX_ADD(SSID_TYPE "overflow")
	SYNTAX_ADD(SSID_TYPE "open")
	SYNTAX_ADD(SSID_TYPE "optimum")
	SYNTAX_ADD(SSID_TYPE "pattern")
	SYNTAX_ADD(SSID_TYPE "placeholder")
	SYNTAX_ADD(SSID_TYPE "points")
	SYNTAX_ADD(SSID_TYPE "poster")
	SYNTAX_ADD(SSID_TYPE "preload")
	SYNTAX_ADD(SSID_TYPE "property")
	SYNTAX_ADD(SSID_TYPE "readonly")
	SYNTAX_ADD(SSID_TYPE "rel")
	SYNTAX_ADD(SSID_TYPE "required")
	SYNTAX_ADD(SSID_TYPE "reversed")
	SYNTAX_ADD(SSID_TYPE "rows")
	SYNTAX_ADD(SSID_TYPE "role")
	SYNTAX_ADD(SSID_TYPE "rowspan")
	SYNTAX_ADD(SSID_TYPE "sandbox")
	SYNTAX_ADD(SSID_TYPE "scope")
	SYNTAX_ADD(SSID_TYPE "selected")
	SYNTAX_ADD(SSID_TYPE "shape")
	SYNTAX_ADD(SSID_TYPE "size")
	SYNTAX_ADD(SSID_TYPE "sizes")
	SYNTAX_ADD(SSID_TYPE "span")
	SYNTAX_ADD(SSID_TYPE "spellcheck")
	SYNTAX_ADD(SSID_TYPE "src")
	SYNTAX_ADD(SSID_TYPE "srcdoc")
	SYNTAX_ADD(SSID_TYPE "srclang")
	SYNTAX_ADD(SSID_TYPE "srcset")
	SYNTAX_ADD(SSID_TYPE "start")
	SYNTAX_ADD(SSID_TYPE "step")
	SYNTAX_ADD(SSID_TYPE "style")
	SYNTAX_ADD(SSID_TYPE "tabindex")
	SYNTAX_ADD(SSID_TYPE "target")
	SYNTAX_ADD(SSID_TYPE "title")
	SYNTAX_ADD(SSID_TYPE "to")
	SYNTAX_ADD(SSID_TYPE "translatetitle")
	SYNTAX_ADD(SSID_TYPE "type")
	SYNTAX_ADD(SSID_TYPE "usemap")
	SYNTAX_ADD(SSID_TYPE "value")
	SYNTAX_ADD(SSID_TYPE "version")
	SYNTAX_ADD(SSID_TYPE "viewBox")
	SYNTAX_ADD(SSID_TYPE "width")
	SYNTAX_ADD(SSID_TYPE "wrap")
	SYNTAX_ADD(SSID_TYPE "x")
	SYNTAX_ADD(SSID_TYPE "y")
	SYNTAX_ADD(SSID_OPERATOR ">")
	SYNTAX_ADD(SSID_OPERATOR "<")
	SYNTAX_ADD(SSID_OPERATOR "/")
	SYNTAX_ADD(SSID_OPERATOR "!")
	SYNTAX_ADD_RANGE(SSID_COMMENT "<!--", "-->")
	SYNTAX_ADD_RANGE(SSID_STRING "\"", "\"")
	SYNTAX_ADD_RANGE(SSID_CHARACTER_LITERAL "'", "'")
SYNTAX_END(syntax_html)

SYNTAX_NEW(syntax_sast)
	SYNTAX_EXT_COUNT(1)
	SYNTAX_ADD_EXT(".s")
	SYNTAX_ADD(SSID_OPERATOR "*")
	SYNTAX_ADD(SSID_OPERATOR "+")
	SYNTAX_ADD_RANGE(SSID_KEYWORD ".", " ")
	SYNTAX_ADD_RANGE(SSID_KEYWORD ".", "\0")
	SYNTAX_ADD_RANGE_NI(SSID_TYPE "%", "*")
	SYNTAX_ADD_RANGE(SSID_TYPE "%", " ")
	SYNTAX_ADD_RANGE(SSID_TYPE "%", "\0")
	SYNTAX_ADD_RANGE(SSID_MACRO "!", " ")
	SYNTAX_ADD_RANGE(SSID_MACRO "!", "\0")
	SYNTAX_ADD_RANGE_NI(SSID_CONST "@", "*")
	SYNTAX_ADD_RANGE(SSID_CONST "@", " ")
	SYNTAX_ADD_RANGE_NI(SSID_CONST "@", "\0")
	SYNTAX_ADD_RANGE(SSID_NUMBER "$", " ")
	SYNTAX_ADD_RANGE(SSID_NUMBER "$", "\0")
	SYNTAX_ADD_RANGE(SSID_STRING "\"", "\"")
	SYNTAX_ADD_RANGE_NI(SSID_CHARACTER_LITERAL "'", " ")
SYNTAX_END(syntax_sast)

char** syntaxes[] = {
	SYNTAXES_ADD(syntax_c)
	SYNTAXES_ADD(syntax_cpp)
	SYNTAXES_ADD(syntax_py)
	SYNTAXES_ADD(syntax_js)
	SYNTAXES_ADD(syntax_java)
	SYNTAXES_ADD(syntax_css)
	SYNTAXES_ADD(syntax_html)
	SYNTAXES_ADD(syntax_sast)
};

#endif